# student_t1's kernels generated by stabilita/gen_student_t2.py (T_FAMILY=t1):
# exact values on both sides of the crossover at nu = 20 and far beyond it,
# the closed expectations against quadrature, and the fifth order against a
# derivative of the fourth.

test_that("student_t1 agrees with exact values from nu = 0.3 to 1e10", {
  # exact values at 250 digits (mpmath, T_FAMILY=t1 gen_student_t2.py
  # --reference) at y = 0.7, mu = 0.2, sigma = 1.3. Every derivative in nu
  # vanishes as a power of 1/nu and is a difference of terms of a lower
  # order: the former kernels lost the fourth order by nu = 1e6 and the
  # quadrature behind the expected third and fourth by nu = 1e3.
  d <- student_t1_distrib()
  ref <- list(
    list(0.3, "gradient", "nu", 1.6737729635911747254),
    list(1e6, "gradient", "nu", 3.1849374035625541421e-13),
    list(1e10, "gradient", "nu", 3.1849375021784360951e-21),
    list(0.3, "hessian", "nu_nu", -7.9758404051582616256),
    list(1e10, "hessian", "nu_nu", -6.3698750043470097394e-31),
    list(0.3, "deriv3", "nu_nu_nu", 60.744697744175557764),
    list(1e6, "deriv3", "nu_nu_nu", 1.9109623829610973548e-24),
    list(0.3, "deriv4", "sigma_sigma_nu_nu", -1.1141490194313975344),
    list(1e10, "deriv4", "sigma_sigma_nu_nu", -3.9570656304223574153e-31),
    list(1e6, "deriv4", "nu_nu_nu_nu", -7.6438494134900364262e-30),
    list(0.3, "deriv5", "nu_nu_nu_nu_nu", 9007.5180594109426699),
    list(1e10, "deriv5", "nu_nu_nu_nu_nu", 3.821925002590453432e-59),
    list(0.3, "expected_hessian", "nu_nu", -8.5905852930804873635),
    list(1e6, "expected_hessian", "nu_nu", -3.499987000039499881e-24),
    list(0.3, "deriv3_expected", "nu_nu_nu", 64.131245886879268105),
    list(1e6, "deriv3_expected", "nu_nu_nu", 2.0999858000794995749e-29),
    list(0.3, "deriv4_expected", "nu_nu_nu_nu", -666.88857705850104884),
    list(1e10, "deriv4_expected", "nu_nu_nu_nu", -1.259999998764000001e-58),
    list(0.3, "dexpected2", "nu_nu_nu_nu", -677.98887079736183669),
    list(1e6, "dexpected2", "nu_nu_nu_nu", -6.9999610001658993336e-35))
  fun <- list(
    gradient = function(th) distrib_gradient(d, 0.7, th),
    hessian = function(th) distrib_hessian(d, 0.7, th),
    deriv3 = function(th) distrib_deriv3(d, 0.7, th),
    deriv4 = function(th) distrib_deriv4(d, 0.7, th),
    deriv5 = function(th) distrib_deriv5(d, 0.7, th),
    expected_hessian = function(th) distrib_expected_hessian(d, 0.7, th),
    deriv3_expected = function(th) distrib_deriv3(d, 0.7, th, expected = TRUE),
    deriv4_expected = function(th) distrib_deriv4(d, 0.7, th, expected = TRUE),
    dexpected2 = function(th) distrib_d2expected_hessian(d, 0.7, th))
  for (r in ref) {
    th <- list(mu = 0.2, sigma = 1.3, nu = r[[1]])
    expect_equal(fun[[r[[2]]]](th)[[r[[3]]]], r[[4]], tolerance = 1e-12,
                 label = paste(r[[2]], r[[3]], r[[1]]))
  }
})

test_that("student_t1's expectations are integrals of its derivatives", {
  d <- student_t1_distrib()
  for (nu in c(0.7, 6.5)) {
    th <- list(mu = 0.2, sigma = 1.3, nu = nu)
    E <- function(fun, key) {
      integrate(function(t) fun(t)[[key]] * distrib_pdf(d, t, th), -Inf, Inf,
                rel.tol = 1e-11)$value
    }
    e3 <- distrib_deriv3(d, 0, th, expected = TRUE)
    e4 <- distrib_deriv4(d, 0, th, expected = TRUE)
    for (key in names(e3)) {
      expect_equal(e3[[key]], E(function(t) distrib_deriv3(d, t, th), key),
                   tolerance = 1e-7, label = paste(key, nu))
    }
    for (key in names(e4)) {
      expect_equal(e4[[key]], E(function(t) distrib_deriv4(d, t, th), key),
                   tolerance = 1e-7, label = paste(key, nu))
    }
  }
})

test_that("student_t1's fifth order is the derivative of its fourth", {
  d <- student_t1_distrib()
  nm <- c("mu", "sigma", "nu")
  th <- list(mu = 0.2, sigma = 1.3, nu = 4.5)
  y <- c(-3.1, -0.4, 0.7, 2.2)
  hi <- distrib_deriv5(d, y, th)
  expect_length(hi, 21)
  for (key in names(hi)) {
    parts <- strsplit(key, "_")[[1]]
    last <- match(parts[5], nm)
    lo_key <- paste(parts[1:4], collapse = "_")
    num <- sapply(seq_along(y), function(i) numDeriv::grad(function(p)
      distrib_deriv4(d, y[i], list(mu = p[1], sigma = p[2], nu = p[3]))[[lo_key]],
      c(0.2, 1.3, 4.5))[last])
    expect_equal(hi[[key]], num, tolerance = 1e-5, label = key)
  }
})

test_that("student_t1's response derivatives are derivatives of each other", {
  d <- student_t1_distrib()
  th <- list(mu = 0.2, sigma = 1.3, nu = 3)
  y <- c(-3.1, -0.4, 0.7, 2.2)
  h <- 1e-5
  for (pr in list(c("distrib_grad_y", "distrib_hess_y"),
                  c("distrib_hess_y", "distrib_deriv3_y"),
                  c("distrib_deriv3_y", "distrib_deriv4_y"))) {
    lo <- get(pr[1]); hi <- get(pr[2])
    expect_equal(hi(d, y, th), (lo(d, y + h, th) - lo(d, y - h, th)) / (2 * h),
                 tolerance = 1e-7, label = pr[2])
  }
  # the mixed derivatives against the parameter derivatives of grad_y
  got <- distrib_cross_y(d, y, th)
  for (i in seq_along(y)) {
    g <- numDeriv::grad(function(p) distrib_grad_y(d, y[i], list(mu = p[1], sigma = p[2],
                                                                  nu = p[3])), c(0.2, 1.3, 3))
    expect_equal(c(got$mu[i], got$sigma[i], got$nu[i]), g, tolerance = 1e-8)
  }
  got <- distrib_hess_y_hess(d, y, th)
  for (i in seq_along(y)) {
    hh <- numDeriv::hessian(function(p) distrib_hess_y(d, y[i], list(mu = p[1], sigma = p[2],
                                                                     nu = p[3])), c(0.2, 1.3, 3))
    expect_equal(c(got$mu_mu[i], got$sigma_sigma[i], got$nu_nu[i], got$mu_sigma[i],
                   got$mu_nu[i], got$sigma_nu[i]),
                 c(hh[1, 1], hh[2, 2], hh[3, 3], hh[1, 2], hh[1, 3], hh[2, 3]),
                 tolerance = 1e-7)
  }
})

test_that("student_t1 passes its own validator to order five", {
  d <- student_t1_distrib()
  set.seed(3)
  res <- check_distrib(d, list(mu = 0.2, sigma = 1.3, nu = 7), orders = 1:5,
                       verbose = FALSE)
  expect_true(all(res$status == "OK"),
              info = paste(res$check[res$status != "OK"], collapse = ", "))
})
