# skewnormal2's kernels generated by stabilita/gen_skewnormal2.py: exact
# values near zero skewness, where the closed forms cancel and the kernels
# read the series of the log-density in gamma1^(1/3), and at the ceiling; the
# expected information from its series and from quadrature; the fifth order
# and the mixed derivatives against derivatives of lower orders.

test_that("skewnormal2 agrees with exact values near zero skewness and at the ceiling", {
  # exact values at 120 digits (mpmath, stabilita/sn2_reference.py) at
  # mu = 0.2, sigma = 1.3. The former chain through skewnormal1 lost 1.3e-5 at
  # the fourth order at gamma1 = 1e-8, and its numerical fifth order every
  # digit below 1e-4.
  d <- skewnormal2_distrib()
  ref <- list(
    list(0.3, 1e-8, "gradient", "gamma1", -0.038075321505892453266),
    list(2.4, -1e-5, "gradient", "gamma1", -0.032122735795800095548),
    list(0.3, 1e-8, "hessian", "gamma1_gamma1", 10344.872635496538648),
    list(2.4, 1e-6, "hessian", "mu_gamma1", -0.7165433610226148278),
    list(0.3, 1e-8, "deriv3", "gamma1_gamma1_gamma1", -689686067896.72034461),
    list(2.4, -1e-5, "deriv3", "gamma1_gamma1_gamma1", -13922518.301223815858),
    list(2.4, 1e-8, "deriv4", "sigma_sigma_gamma1_gamma1", 125839.74727274787168),
    list(0.3, -1e-5, "deriv4", "sigma_sigma_gamma1_gamma1", -4.3371758094570812597),
    list(0.3, 1e-6, "deriv5", "mu_gamma1_gamma1_gamma1_gamma1", 127803737235257.40163),
    list(-1.7, 0.99, "hessian", "gamma1_gamma1", -210310.24098256650789),
    list(-1.7, 0.99, "deriv4", "sigma_sigma_gamma1_gamma1", -30125575.2005339758),
    list(0.3, 0.99, "deriv5", "gamma1_gamma1_gamma1_gamma1_gamma1", -4.6174060427465520815))
  fun <- list(gradient = distrib_gradient, hessian = distrib_hessian,
              deriv3 = distrib_deriv3, deriv4 = distrib_deriv4, deriv5 = distrib_deriv5)
  for (r in ref) {
    th <- list(mu = 0.2, sigma = 1.3, gamma1 = r[[2]])
    expect_equal(fun[[r[[3]]]](d, r[[1]], th)[[r[[4]]]], r[[5]], tolerance = 1e-10,
                 label = paste(r[[3]], r[[4]], r[[2]]))
  }
})

test_that("the score is finite at zero skewness and the higher orders are rejected", {
  d <- skewnormal2_distrib()
  y <- c(-1.7, 0.3, 2.4)
  at <- function(g) list(mu = 0.2, sigma = 1.3, gamma1 = g)
  g0 <- distrib_gradient(d, y, at(0))
  expect_true(all(is.finite(unlist(g0))))
  # the score approaches its value at zero as gamma1^(1/3)
  expect_equal(g0$gamma1, distrib_gradient(d, y, at(1e-30))$gamma1, tolerance = 1e-9)
  expect_equal(g0$gamma1, distrib_gradient(d, y, at(-1e-30))$gamma1, tolerance = 1e-9)
  for (f in list(distrib_hessian, distrib_deriv3, distrib_deriv4, distrib_deriv5,
                 distrib_dexpected_hessian)) {
    expect_error(f(d, y, at(0)), "zero")
  }
  # the response derivatives hold at zero, where they are the gaussian's
  expect_equal(distrib_deriv3_y(d, y, at(0)), rep(0, 3))
  expect_equal(distrib_hess_y(d, y, at(0)), rep(-1 / 1.3^2, 3))
})

test_that("the expected information is its series near zero and a quadrature beyond", {
  # exact values: mpmath quadrature at 50 digits of the exact observed
  # Hessian (stabilita/sn2_expected_ref.py), at mu = 0, sigma = 1
  d <- skewnormal2_distrib()
  ref <- list(
    list(1e-8, "gamma1_gamma1", -0.16666692969952246927),
    list(1e-8, "mu_gamma1", 3.1407107504866929309e-12),
    list(1e-6, "sigma_gamma1", 5.0001603665251799486e-7),
    list(1e-2, "gamma1_gamma1", -0.16777177399467468201),
    list(1e-2, "mu_gamma1", 0.00026202745639535858987),
    list(1e-2, "sigma_gamma1", 0.0050188968720147546439))
  for (r in ref) {
    e <- distrib_expected_hessian(d, 0, list(mu = 0, sigma = 1, gamma1 = r[[1]]))
    expect_equal(e[[r[[2]]]], r[[3]], tolerance = 1e-10, label = paste(r[[2]], r[[1]]))
  }
  # at zero skewness: diag(1, 2, 1/6)/sigma^2 with the sign of a Hessian
  e0 <- distrib_expected_hessian(d, 0, list(mu = 1, sigma = 2, gamma1 = 0))
  expect_equal(unlist(e0), c(mu_mu = -1 / 4, sigma_sigma = -2 / 4,
                             gamma1_gamma1 = -1 / 6, mu_sigma = 0,
                             mu_gamma1 = 0, sigma_gamma1 = 0), tolerance = 1e-14)
  # the two routes meet at the bound
  ge <- distributions7:::sn2_ge()
  lo <- unlist(distrib_expected_hessian(d, 0, list(mu = 0, sigma = 1, gamma1 = ge * (1 - 1e-12))))
  hi <- unlist(distrib_expected_hessian(d, 0, list(mu = 0, sigma = 1, gamma1 = ge)))
  expect_equal(lo, hi, tolerance = 1e-10)
  # observations on both sides of the bound in one call
  gs <- c(1e-6, 0.4, -2e-4, -0.7)
  mixed <- distrib_expected_hessian(d, rep(0, 4), list(mu = 0, sigma = 1.3, gamma1 = gs))
  for (i in seq_along(gs)) {
    one <- distrib_expected_hessian(d, 0, list(mu = 0, sigma = 1.3, gamma1 = gs[i]))
    expect_equal(vapply(mixed, `[`, 0, i), unlist(one), tolerance = 1e-14)
  }
})

test_that("the derivatives of the expected information are its derivatives", {
  d <- skewnormal2_distrib()
  # near zero the information carries a term in gamma1^(2/3) and a difference
  # quotient is the weak side; there the reference is a central difference at
  # 50 digits of the exact quadrature (stabilita/sn2_expected_ref.py)
  d1 <- distrib_dexpected_hessian(d, 0, list(mu = 0, sigma = 1, gamma1 = 1e-4))
  expect_equal(d1$sigma_sigma_gamma1, 0.0536320521103328, tolerance = 1e-12)
  expect_equal(d1$mu_mu_gamma1, -0.000100071573721404, tolerance = 1e-12)
  nm <- c("mu", "sigma", "gamma1")
  for (g in c(-0.05, 0.4)) {
    p0 <- c(0.2, 1.3, g)
    d1 <- distrib_dexpected_hessian(d, 0, list(mu = 0.2, sigma = 1.3, gamma1 = g))
    E <- function(p) unlist(distrib_expected_hessian(d, 0, list(mu = p[1], sigma = p[2],
                                                                gamma1 = p[3])))
    J <- numDeriv::jacobian(E, p0)
    hn <- names(E(p0))
    for (a in seq_along(hn)) for (j in 1:3) {
      expect_equal(d1[[paste(hn[a], nm[j], sep = "_")]], J[a, j], tolerance = 1e-6,
                   label = paste(hn[a], nm[j], g))
    }
  }
})

test_that("skewnormal2's fifth order is the derivative of its fourth", {
  d <- skewnormal2_distrib()
  nm <- c("mu", "sigma", "gamma1")
  y <- c(-1.7, 0.3, 2.4)
  for (g in c(0.4, -0.05)) {
    hi <- distrib_deriv5(d, y, list(mu = 0.2, sigma = 1.3, gamma1 = g))
    expect_length(hi, 21)
    for (key in names(hi)) {
      parts <- strsplit(key, "_")[[1]]
      last <- match(parts[5], nm)
      lo_key <- paste(parts[1:4], collapse = "_")
      num <- sapply(seq_along(y), function(i) numDeriv::grad(function(p)
        distrib_deriv4(d, y[i], list(mu = p[1], sigma = p[2], gamma1 = p[3]))[[lo_key]],
        c(0.2, 1.3, g))[last])
      expect_equal(hi[[key]], num, tolerance = 1e-5, label = paste(key, g))
    }
  }
})

test_that("skewnormal2's mixed derivatives are derivatives of its response derivatives", {
  d <- skewnormal2_distrib()
  y <- c(-1.7, 0.3, 2.4)
  th <- list(mu = 0.2, sigma = 1.3, gamma1 = 0.4)
  p0 <- c(0.2, 1.3, 0.4)
  cy <- distrib_cross_y(d, y, th)
  hh <- distrib_hess_y_hess(d, y, th)
  for (i in seq_along(y)) {
    g <- numDeriv::grad(function(p) distrib_grad_y(d, y[i], list(mu = p[1], sigma = p[2],
                                                                  gamma1 = p[3])), p0)
    expect_equal(c(cy$mu[i], cy$sigma[i], cy$gamma1[i]), g, tolerance = 1e-8)
    H <- numDeriv::hessian(function(p) distrib_hess_y(d, y[i], list(mu = p[1], sigma = p[2],
                                                                   gamma1 = p[3])), p0)
    expect_equal(c(hh$mu_mu[i], hh$sigma_sigma[i], hh$gamma1_gamma1[i], hh$mu_sigma[i],
                   hh$mu_gamma1[i], hh$sigma_gamma1[i]),
                 c(H[1, 1], H[2, 2], H[3, 3], H[1, 2], H[1, 3], H[2, 3]), tolerance = 1e-7)
  }
  h <- 1e-5
  expect_equal(distrib_deriv3_y(d, y, th),
               (distrib_hess_y(d, y + h, th) - distrib_hess_y(d, y - h, th)) / (2 * h),
               tolerance = 1e-7)
})

test_that("skewnormal2 passes its own validator to order five", {
  d <- skewnormal2_distrib()
  set.seed(3)
  res <- check_distrib(d, list(mu = 0.2, sigma = 1.3, gamma1 = 0.4), orders = 1:5,
                       verbose = FALSE)
  expect_true(all(res$status == "OK"),
              info = paste(res$check[res$status != "OK"], collapse = ", "))
})


test_that("the centered skew normal's cdf gradient at zero skewness is its limit", {
  # F = Phi(z) - gamma1 (z^2 - 1) phi(z)/6 + O(gamma1^(4/3)): the limit against
  # the mapped route at r = gamma1^(1/3) = 1e-3, 2e-3, 4e-3, extrapolated to
  # r = 0 through the terms in r and r^2
  d <- skewnormal2_distrib()
  q <- c(-1.3, 0.2, 2.5)
  for (lt in c(TRUE, FALSE)) for (lg in c(TRUE, FALSE)) {
    f <- function(g) unlist(distrib_grad_cdf(d, q, list(mu = 0.4, sigma = 1.7, gamma1 = g),
                                             lower.tail = lt, log = lg))
    at0 <- f(0)
    r <- c(1e-3, 2e-3, 4e-3)
    v <- sapply(r^3, f)
    # values at r = 0 by quadratic extrapolation in r
    ext <- v[, 1] * 8 / 3 - v[, 2] * 2 + v[, 3] / 3
    expect_equal(at0, ext, tolerance = 1e-6)
  }
  # rows with and without zero skewness together
  mix <- distrib_grad_cdf(d, q, list(mu = 0.4, sigma = 1.7, gamma1 = c(0, 0.3, 0)))
  one <- distrib_grad_cdf(d, q[2], list(mu = 0.4, sigma = 1.7, gamma1 = 0.3))
  expect_equal(vapply(mix, `[`, 0, 2), unlist(one))
  # the higher orders diverge in gamma1 there, as the log-density's do
  expect_error(distrib_hess_cdf(d, q, list(mu = 0.4, sigma = 1.7, gamma1 = 0)),
               "infinite at zero")
})
