#include <Rcpp.h>
#include <cmath>
#include <algorithm>
#include <string>
#include <vector>
#include "pt_pseudohuber2.h"
#include "pt_pseudohuber2_table.h"
#include "pt_sqrt.h"
using namespace Rcpp;

// The pseudo-Huber family in its standard-deviation parametrization
// (mu, sigma, nu), sigma being the standard deviation of Y. With
//   R(nu) = sqrt(nu) K_2(sqrt(nu)) / K_1(sqrt(nu)),   r = y - mu,
//   Q = nu + R(nu) r^2 / sigma^2,   D = sqrt(Q),
// the log-density is
//   l = -D - log 2 - log sigma + h(nu),
//   h(nu) = -log(nu)/4 + log K_2(sqrt(nu))/2 - 3 log K_1(sqrt(nu))/2.
//
// Orders one and two are written out per component in pt_pseudohuber2.h,
// with the diagonal of order three the quadrature reads. Orders three to
// five differentiate the data part -A/sigma, A = sqrt(nu sigma^2 + R r^2),
// r = y - mu, in closed forms written in u = r/A and powers of 1/A
// (pt_pseudohuber2_table.h, generated by stabilita/gen_pseudohuber2_table.py).
// Each kernel computes R and h to its own order and nothing above it.
//
// R and h (nu_part(), in pt_pseudohuber2.h) are read off
// L_n(nu) = log K_n(sqrt(nu)), n = 1, 2. In t = sqrt(nu)
// the ratios K_n^(j)(t) / K_n(t) are sums of K_m(t) / K_n(t), formed with the
// exponentially scaled Bessel functions so that the e^-t factors cancel; the
// derivatives of log K_n in t follow from those ratios by the moment-cumulant
// relations, and the derivatives in nu from Faa di Bruno through t(nu).

namespace {

using d7::NuPart;
using d7::nu_part;

// ---- orders three to five ----------------------------------------------

// the components of order m: the counts of mu-, sigma- and nu-derivatives,
// in lexicographic order of the parameter positions, the order in which
// ph2_hd_3/4/5 fill their output
struct Component {
  int nmu, nsig, nnu;
};

const std::vector<Component> &compiled(int m) {
  static std::vector<Component> cache[6];
  if (!cache[m].empty()) return cache[m];
  std::vector<int> idx(m, 0);
  while (true) {
    Component comp;
    comp.nmu = comp.nsig = comp.nnu = 0;
    for (int e = 0; e < m; e++) {
      if (idx[e] == 0) comp.nmu++; else if (idx[e] == 1) comp.nsig++; else comp.nnu++;
    }
    cache[m].push_back(comp);
    int k = m - 1;
    while (k >= 0 && idx[k] == 2) k--;
    if (k < 0) break;
    idx[k]++;
    for (int j = k + 1; j < m; j++) idx[j] = idx[k];
  }
  return cache[m];
}

std::string comp_name(const std::vector<int> &idx) {
  const char *nm[3] = {"mu", "sigma", "nu"};
  std::string key;
  for (size_t e = 0; e < idx.size(); e++) {
    if (e) key += "_";
    key += nm[idx[e]];
  }
  return key;
}

List high_order(int m, NumericVector y, NumericVector mu, NumericVector sigma,
                NumericVector nu) {
  const int n = y.size();
  const bool mu_s = mu.size() == 1, sg_s = sigma.size() == 1,
             nu_s = nu.size() == 1;
  const std::vector<Component> &C = compiled(m);
  const int nc = C.size();
  std::vector<NumericVector> res;
  for (int c = 0; c < nc; c++) res.push_back(NumericVector(n));
  NuPart np = {{0}, {0}};
  double last_nu = NA_REAL;
  // (d/dsigma)^m (-log sigma) = (-1)^m (m-1)! / sigma^m
  double fm = 1.0;
  for (int k = 2; k < m; k++) fm *= k;
  fm *= (m % 2) ? -1.0 : 1.0;
  for (int i = 0; i < n; i++) {
    const double m_i = mu_s ? mu[0] : mu[i];
    const double s = sg_s ? sigma[0] : sigma[i];
    const double v = nu_s ? nu[0] : nu[i];
    if (!(v == last_nu)) { nu_part(v, m, np); last_nu = v; }
    // the data part -A/sigma, A = sqrt(nu sigma^2 + R r^2), differentiated
    // in (mu, sigma, nu) and written in u = r/A and powers of 1/A
    // (pt_pseudohuber2_table.h). The Faa di Bruno sum over the partials of Q
    // it replaces cancelled from |z| near 1e6, and a chain from d/dz from
    // |z| near 1e8; A is formed by hypot() so that r^2 never overflows.
    const double r = y[i] - m_i;
    const double cA = s * d7::sqrt_cr(v);
    const double A = std::hypot(d7::sqrt_cr(np.R[0]) * r, cA);
    const double iA = 1.0 / A, uu = r * iA;
    const double is = 1.0 / s;
    double comp[21];
    if (m == 3) d7::ph2_hd_3(uu, v, iA, is, np.R, comp);
    else if (m == 4) d7::ph2_hd_4(uu, v, iA, is, np.R, comp);
    else d7::ph2_hd_5(uu, v, iA, is, np.R, comp);
    for (int c = 0; c < nc; c++) {
      const Component &cp = C[c];
      const double dD = -comp[c];
      double out = -dD;
      if (cp.nsig == m) out += fm * std::pow(is, m);
      if (cp.nnu == m) out += np.h[m];
      res[c][i] = out;
    }
  }
  // names from the same enumeration
  List out(nc);
  CharacterVector names(nc);
  std::vector<int> idx(m, 0);
  for (int c = 0; c < nc; c++) {
    out[c] = res[c];
    names[c] = comp_name(idx);
    int k = m - 1;
    while (k >= 0 && idx[k] == 2) k--;
    if (k < 0) break;
    idx[k]++;
    for (int j = k + 1; j < m; j++) idx[j] = idx[k];
  }
  out.attr("names") = names;
  return out;
}

}  // namespace

// [[Rcpp::export]]
List pseudohuber2_gradient_cpp(NumericVector y, NumericVector mu,
                               NumericVector sigma, NumericVector nu) {
  const int n = y.size();
  const bool mu_s = mu.size() == 1, sg_s = sigma.size() == 1,
             nu_s = nu.size() == 1;
  NumericVector g_mu(n), g_sigma(n), g_nu(n);
  NuPart np = {{0}, {0}};
  double last_nu = NA_REAL;
  for (int i = 0; i < n; i++) {
    const double m_i = mu_s ? mu[0] : mu[i];
    const double s = sg_s ? sigma[0] : sigma[i];
    const double v = nu_s ? nu[0] : nu[i];
    if (!(v == last_nu)) { nu_part(v, 1, np); last_nu = v; }
    const double z = (y[i] - m_i) / s;
    const d7::Ph2Z P = d7::ph2_z(z, v, np.R[0]);
    g_mu[i] = d7::pseudohuber2_score_mu(s, P, np);
    g_sigma[i] = d7::pseudohuber2_score_sigma(z, s, P, np);
    g_nu[i] = d7::pseudohuber2_score_nu(z, P, np);
  }
  return List::create(Named("mu") = g_mu, Named("sigma") = g_sigma,
                      Named("nu") = g_nu);
}

// [[Rcpp::export]]
List pseudohuber2_hessian_cpp(NumericVector y, NumericVector mu,
                              NumericVector sigma, NumericVector nu) {
  const int n = y.size();
  const bool mu_s = mu.size() == 1, sg_s = sigma.size() == 1,
             nu_s = nu.size() == 1;
  NumericVector h_mm(n), h_ss(n), h_nn(n), h_ms(n), h_mn(n), h_sn(n);
  NuPart np = {{0}, {0}};
  double last_nu = NA_REAL;
  for (int i = 0; i < n; i++) {
    const double m_i = mu_s ? mu[0] : mu[i];
    const double s = sg_s ? sigma[0] : sigma[i];
    const double v = nu_s ? nu[0] : nu[i];
    if (!(v == last_nu)) { nu_part(v, 2, np); last_nu = v; }
    const double z = (y[i] - m_i) / s;
    const double R0 = np.R[0], R1 = np.R[1];
    const d7::Ph2Z P = d7::ph2_z(z, v, R0);
    const double zD = P.zD, zz = z * zD, s2 = s * s;
    double qn, qnD;
    d7::ph2_qn(z, P, np, &qn, &qnD);
    // l_xy = -(Q_xy / (2 D) - (Q_x / D)(Q_y / D) / (4 D)) + pure terms,
    // with Q_mu / D = -2 R zD / sigma and Q_sigma / D = -2 R z zD / sigma
    h_mm[i] = d7::pseudohuber2_hess_mu_mu(s, P, np, v);
    h_ss[i] = d7::pseudohuber2_hess_sigma_sigma(z, s, P, np, v);
    h_nn[i] = d7::pseudohuber2_hess_nu_nu(z, P, np);
    const double vD2 = v / (P.D * P.D);
    // 2 - R zD^2 = 1 + nu/D^2 and 1 - R zD^2 / 2 = (1 + nu/D^2)/2 exactly
    h_ms[i] = -R0 * zD * (1.0 + vD2) / s2;
    h_mn[i] = zD * (0.5 * R1 * (1.0 + vD2) - 0.5 * R0 / (P.D * P.D)) / s;
    h_sn[i] = zz * (0.5 * R1 * (1.0 + vD2) - 0.5 * R0 / (P.D * P.D)) / s;
  }
  return List::create(Named("mu_mu") = h_mm, Named("sigma_sigma") = h_ss,
                      Named("nu_nu") = h_nn, Named("mu_sigma") = h_ms,
                      Named("mu_nu") = h_mn, Named("sigma_nu") = h_sn);
}

// [[Rcpp::export]]
List pseudohuber2_deriv3_cpp(NumericVector y, NumericVector mu,
                             NumericVector sigma, NumericVector nu) {
  return high_order(3, y, mu, sigma, nu);
}

// [[Rcpp::export]]
List pseudohuber2_deriv4_cpp(NumericVector y, NumericVector mu,
                             NumericVector sigma, NumericVector nu) {
  return high_order(4, y, mu, sigma, nu);
}

// [[Rcpp::export]]
List pseudohuber2_deriv5_cpp(NumericVector y, NumericVector mu,
                             NumericVector sigma, NumericVector nu) {
  return high_order(5, y, mu, sigma, nu);
}

// R(nu) and the log normalizing term h(nu), for the density in R.
// [[Rcpp::export]]
List pseudohuber2_nu_terms_cpp(NumericVector nu) {
  const int n = nu.size();
  NumericVector R(n), h(n);
  for (int i = 0; i < n; i++) {
    const double v = nu[i];
    const d7::Ph2Terms T = d7::pseudohuber2_terms(v);
    R[i] = T.R;
    h[i] = T.h;
  }
  return List::create(Named("R") = R, Named("h") = h);
}
