// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bernoulli_gradient_cpp
List bernoulli_gradient_cpp(NumericVector y, NumericVector mu);
RcppExport SEXP _distributions7_bernoulli_gradient_cpp(SEXP ySEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(bernoulli_gradient_cpp(y, mu));
    return rcpp_result_gen;
END_RCPP
}
// bernoulli_hessian_cpp
List bernoulli_hessian_cpp(NumericVector y, NumericVector mu);
RcppExport SEXP _distributions7_bernoulli_hessian_cpp(SEXP ySEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(bernoulli_hessian_cpp(y, mu));
    return rcpp_result_gen;
END_RCPP
}
// bernoulli_expected_hessian_cpp
List bernoulli_expected_hessian_cpp(NumericVector y, NumericVector mu);
RcppExport SEXP _distributions7_bernoulli_expected_hessian_cpp(SEXP ySEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(bernoulli_expected_hessian_cpp(y, mu));
    return rcpp_result_gen;
END_RCPP
}
// beta_gradient_cpp
List beta_gradient_cpp(NumericVector y, NumericVector mu, NumericVector phi);
RcppExport SEXP _distributions7_beta_gradient_cpp(SEXP ySEXP, SEXP muSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_gradient_cpp(y, mu, phi));
    return rcpp_result_gen;
END_RCPP
}
// beta_hessian_cpp
List beta_hessian_cpp(NumericVector y, NumericVector mu, NumericVector phi);
RcppExport SEXP _distributions7_beta_hessian_cpp(SEXP ySEXP, SEXP muSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_hessian_cpp(y, mu, phi));
    return rcpp_result_gen;
END_RCPP
}
// beta_expected_hessian_cpp
List beta_expected_hessian_cpp(NumericVector y, NumericVector mu, NumericVector phi);
RcppExport SEXP _distributions7_beta_expected_hessian_cpp(SEXP ySEXP, SEXP muSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_expected_hessian_cpp(y, mu, phi));
    return rcpp_result_gen;
END_RCPP
}
// binomial_gradient_cpp
List binomial_gradient_cpp(NumericVector y, NumericVector mu, NumericVector size);
RcppExport SEXP _distributions7_binomial_gradient_cpp(SEXP ySEXP, SEXP muSEXP, SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type size(sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(binomial_gradient_cpp(y, mu, size));
    return rcpp_result_gen;
END_RCPP
}
// binomial_hessian_cpp
List binomial_hessian_cpp(NumericVector y, NumericVector mu, NumericVector size);
RcppExport SEXP _distributions7_binomial_hessian_cpp(SEXP ySEXP, SEXP muSEXP, SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type size(sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(binomial_hessian_cpp(y, mu, size));
    return rcpp_result_gen;
END_RCPP
}
// binomial_expected_hessian_cpp
List binomial_expected_hessian_cpp(NumericVector y, NumericVector mu, NumericVector size);
RcppExport SEXP _distributions7_binomial_expected_hessian_cpp(SEXP ySEXP, SEXP muSEXP, SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type size(sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(binomial_expected_hessian_cpp(y, mu, size));
    return rcpp_result_gen;
END_RCPP
}
// cauchy_gradient_cpp
List cauchy_gradient_cpp(NumericVector y, NumericVector mu, NumericVector sigma);
RcppExport SEXP _distributions7_cauchy_gradient_cpp(SEXP ySEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(cauchy_gradient_cpp(y, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// cauchy_hessian_cpp
List cauchy_hessian_cpp(NumericVector y, NumericVector mu, NumericVector sigma);
RcppExport SEXP _distributions7_cauchy_hessian_cpp(SEXP ySEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(cauchy_hessian_cpp(y, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// cauchy_expected_hessian_cpp
List cauchy_expected_hessian_cpp(NumericVector y, NumericVector mu, NumericVector sigma);
RcppExport SEXP _distributions7_cauchy_expected_hessian_cpp(SEXP ySEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(cauchy_expected_hessian_cpp(y, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// gamma_gradient_cpp
List gamma_gradient_cpp(NumericVector y, NumericVector mu, NumericVector sigma2);
RcppExport SEXP _distributions7_gamma_gradient_cpp(SEXP ySEXP, SEXP muSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma2(sigma2SEXP);
    rcpp_result_gen = Rcpp::wrap(gamma_gradient_cpp(y, mu, sigma2));
    return rcpp_result_gen;
END_RCPP
}
// gamma_hessian_cpp
List gamma_hessian_cpp(NumericVector y, NumericVector mu, NumericVector sigma2);
RcppExport SEXP _distributions7_gamma_hessian_cpp(SEXP ySEXP, SEXP muSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma2(sigma2SEXP);
    rcpp_result_gen = Rcpp::wrap(gamma_hessian_cpp(y, mu, sigma2));
    return rcpp_result_gen;
END_RCPP
}
// gamma_expected_hessian_cpp
List gamma_expected_hessian_cpp(NumericVector y, NumericVector mu, NumericVector sigma2);
RcppExport SEXP _distributions7_gamma_expected_hessian_cpp(SEXP ySEXP, SEXP muSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma2(sigma2SEXP);
    rcpp_result_gen = Rcpp::wrap(gamma_expected_hessian_cpp(y, mu, sigma2));
    return rcpp_result_gen;
END_RCPP
}
// gaussian_gradient_cpp
List gaussian_gradient_cpp(NumericVector y, NumericVector mu, NumericVector sigma);
RcppExport SEXP _distributions7_gaussian_gradient_cpp(SEXP ySEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussian_gradient_cpp(y, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// gaussian_hessian_cpp
List gaussian_hessian_cpp(NumericVector y, NumericVector mu, NumericVector sigma);
RcppExport SEXP _distributions7_gaussian_hessian_cpp(SEXP ySEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussian_hessian_cpp(y, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// gaussian_expected_hessian_cpp
List gaussian_expected_hessian_cpp(NumericVector y, NumericVector mu, NumericVector sigma);
RcppExport SEXP _distributions7_gaussian_expected_hessian_cpp(SEXP ySEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussian_expected_hessian_cpp(y, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// invgauss_gradient_cpp
List invgauss_gradient_cpp(NumericVector y, NumericVector mu, NumericVector phi);
RcppExport SEXP _distributions7_invgauss_gradient_cpp(SEXP ySEXP, SEXP muSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(invgauss_gradient_cpp(y, mu, phi));
    return rcpp_result_gen;
END_RCPP
}
// invgauss_hessian_cpp
List invgauss_hessian_cpp(NumericVector y, NumericVector mu, NumericVector phi);
RcppExport SEXP _distributions7_invgauss_hessian_cpp(SEXP ySEXP, SEXP muSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(invgauss_hessian_cpp(y, mu, phi));
    return rcpp_result_gen;
END_RCPP
}
// invgauss_expected_hessian_cpp
List invgauss_expected_hessian_cpp(NumericVector y, NumericVector mu, NumericVector phi);
RcppExport SEXP _distributions7_invgauss_expected_hessian_cpp(SEXP ySEXP, SEXP muSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(invgauss_expected_hessian_cpp(y, mu, phi));
    return rcpp_result_gen;
END_RCPP
}
// logistic_gradient_cpp
List logistic_gradient_cpp(NumericVector y, NumericVector mu, NumericVector sigma);
RcppExport SEXP _distributions7_logistic_gradient_cpp(SEXP ySEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(logistic_gradient_cpp(y, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// logistic_hessian_cpp
List logistic_hessian_cpp(NumericVector y, NumericVector mu, NumericVector sigma);
RcppExport SEXP _distributions7_logistic_hessian_cpp(SEXP ySEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(logistic_hessian_cpp(y, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// logistic_expected_hessian_cpp
List logistic_expected_hessian_cpp(NumericVector y, NumericVector mu, NumericVector sigma);
RcppExport SEXP _distributions7_logistic_expected_hessian_cpp(SEXP ySEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(logistic_expected_hessian_cpp(y, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// poisson_gradient_cpp
List poisson_gradient_cpp(NumericVector y, NumericVector mu);
RcppExport SEXP _distributions7_poisson_gradient_cpp(SEXP ySEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(poisson_gradient_cpp(y, mu));
    return rcpp_result_gen;
END_RCPP
}
// poisson_hessian_cpp
List poisson_hessian_cpp(NumericVector y, NumericVector mu);
RcppExport SEXP _distributions7_poisson_hessian_cpp(SEXP ySEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(poisson_hessian_cpp(y, mu));
    return rcpp_result_gen;
END_RCPP
}
// poisson_expected_hessian_cpp
List poisson_expected_hessian_cpp(NumericVector y, NumericVector mu);
RcppExport SEXP _distributions7_poisson_expected_hessian_cpp(SEXP ySEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(poisson_expected_hessian_cpp(y, mu));
    return rcpp_result_gen;
END_RCPP
}
// series_cpp
double series_cpp(Function f, double start, double end, int step, double tol, int maxit, bool reltol);
RcppExport SEXP _distributions7_series_cpp(SEXP fSEXP, SEXP startSEXP, SEXP endSEXP, SEXP stepSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP reltolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    Rcpp::traits::input_parameter< double >::type start(startSEXP);
    Rcpp::traits::input_parameter< double >::type end(endSEXP);
    Rcpp::traits::input_parameter< int >::type step(stepSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< bool >::type reltol(reltolSEXP);
    rcpp_result_gen = Rcpp::wrap(series_cpp(f, start, end, step, tol, maxit, reltol));
    return rcpp_result_gen;
END_RCPP
}
// student_t_gradient_cpp
List student_t_gradient_cpp(NumericVector y, NumericVector mu, NumericVector sigma, NumericVector nu);
RcppExport SEXP _distributions7_student_t_gradient_cpp(SEXP ySEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(student_t_gradient_cpp(y, mu, sigma, nu));
    return rcpp_result_gen;
END_RCPP
}
// student_t_hessian_cpp
List student_t_hessian_cpp(NumericVector y, NumericVector mu, NumericVector sigma, NumericVector nu);
RcppExport SEXP _distributions7_student_t_hessian_cpp(SEXP ySEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(student_t_hessian_cpp(y, mu, sigma, nu));
    return rcpp_result_gen;
END_RCPP
}
// student_t_expected_hessian_cpp
List student_t_expected_hessian_cpp(NumericVector y, NumericVector mu, NumericVector sigma, NumericVector nu);
RcppExport SEXP _distributions7_student_t_expected_hessian_cpp(SEXP ySEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(student_t_expected_hessian_cpp(y, mu, sigma, nu));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_distributions7_bernoulli_gradient_cpp", (DL_FUNC) &_distributions7_bernoulli_gradient_cpp, 2},
    {"_distributions7_bernoulli_hessian_cpp", (DL_FUNC) &_distributions7_bernoulli_hessian_cpp, 2},
    {"_distributions7_bernoulli_expected_hessian_cpp", (DL_FUNC) &_distributions7_bernoulli_expected_hessian_cpp, 2},
    {"_distributions7_beta_gradient_cpp", (DL_FUNC) &_distributions7_beta_gradient_cpp, 3},
    {"_distributions7_beta_hessian_cpp", (DL_FUNC) &_distributions7_beta_hessian_cpp, 3},
    {"_distributions7_beta_expected_hessian_cpp", (DL_FUNC) &_distributions7_beta_expected_hessian_cpp, 3},
    {"_distributions7_binomial_gradient_cpp", (DL_FUNC) &_distributions7_binomial_gradient_cpp, 3},
    {"_distributions7_binomial_hessian_cpp", (DL_FUNC) &_distributions7_binomial_hessian_cpp, 3},
    {"_distributions7_binomial_expected_hessian_cpp", (DL_FUNC) &_distributions7_binomial_expected_hessian_cpp, 3},
    {"_distributions7_cauchy_gradient_cpp", (DL_FUNC) &_distributions7_cauchy_gradient_cpp, 3},
    {"_distributions7_cauchy_hessian_cpp", (DL_FUNC) &_distributions7_cauchy_hessian_cpp, 3},
    {"_distributions7_cauchy_expected_hessian_cpp", (DL_FUNC) &_distributions7_cauchy_expected_hessian_cpp, 3},
    {"_distributions7_gamma_gradient_cpp", (DL_FUNC) &_distributions7_gamma_gradient_cpp, 3},
    {"_distributions7_gamma_hessian_cpp", (DL_FUNC) &_distributions7_gamma_hessian_cpp, 3},
    {"_distributions7_gamma_expected_hessian_cpp", (DL_FUNC) &_distributions7_gamma_expected_hessian_cpp, 3},
    {"_distributions7_gaussian_gradient_cpp", (DL_FUNC) &_distributions7_gaussian_gradient_cpp, 3},
    {"_distributions7_gaussian_hessian_cpp", (DL_FUNC) &_distributions7_gaussian_hessian_cpp, 3},
    {"_distributions7_gaussian_expected_hessian_cpp", (DL_FUNC) &_distributions7_gaussian_expected_hessian_cpp, 3},
    {"_distributions7_invgauss_gradient_cpp", (DL_FUNC) &_distributions7_invgauss_gradient_cpp, 3},
    {"_distributions7_invgauss_hessian_cpp", (DL_FUNC) &_distributions7_invgauss_hessian_cpp, 3},
    {"_distributions7_invgauss_expected_hessian_cpp", (DL_FUNC) &_distributions7_invgauss_expected_hessian_cpp, 3},
    {"_distributions7_logistic_gradient_cpp", (DL_FUNC) &_distributions7_logistic_gradient_cpp, 3},
    {"_distributions7_logistic_hessian_cpp", (DL_FUNC) &_distributions7_logistic_hessian_cpp, 3},
    {"_distributions7_logistic_expected_hessian_cpp", (DL_FUNC) &_distributions7_logistic_expected_hessian_cpp, 3},
    {"_distributions7_poisson_gradient_cpp", (DL_FUNC) &_distributions7_poisson_gradient_cpp, 2},
    {"_distributions7_poisson_hessian_cpp", (DL_FUNC) &_distributions7_poisson_hessian_cpp, 2},
    {"_distributions7_poisson_expected_hessian_cpp", (DL_FUNC) &_distributions7_poisson_expected_hessian_cpp, 2},
    {"_distributions7_series_cpp", (DL_FUNC) &_distributions7_series_cpp, 7},
    {"_distributions7_student_t_gradient_cpp", (DL_FUNC) &_distributions7_student_t_gradient_cpp, 4},
    {"_distributions7_student_t_hessian_cpp", (DL_FUNC) &_distributions7_student_t_hessian_cpp, 4},
    {"_distributions7_student_t_expected_hessian_cpp", (DL_FUNC) &_distributions7_student_t_expected_hessian_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_distributions7(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
