#' @include gpd_distrib.R reparam_maps.R y_higher.R cross2_derivatives.R cross_theta2_derivatives.R higher_derivatives.R link_scale.R cdf_higher.R generics.R
NULL

# The generalized Pareto's derivatives of orders three to five, those in the
# response and those of the distribution function come from the compiled
# kernels of src/gpd.cpp, generated by stabilita/gen_gpd.py. gpd_components()
# below is an independent assembly of orders one to four, kept as the
# reference the tests compare the kernels with.
#
# Its construction:
#
# Splitting the log-density as
#
#   l = -log(sigma) - L - W,   L = log(t),  W = L/xi,  t = 1 + xi y/sigma,
#
# separates the part that is analytic at xi = 0 from the part that is not
# written that way. L is a logarithm of a function whose partials are
# elementary and vanish beyond first order in xi, so fdb2()'s written-out
# template covers it. W = L/xi has a removable singularity: the Leibniz form
#
#   d^{a,b} W = sum_j C(b,j) d^{a,j} L * d^{b-j}(1/xi),
#
# carries terms of size xi^-(b+1) that cancel against each other, so below a
# measured threshold it is replaced by the series the cancellation leaves,
#
#   W = sum_{k >= 0} (-1)^k xi^k z^(k+1) / (k+1),   z = y/sigma,
#
# differentiated term by term. The threshold is on xi*z and not on xi: at
# order b the Leibniz terms are of size z xi^-b against an answer of size
# z^(b+1), so the relative cancellation is (xi z)^-b and the accuracy is
# eps (xi z)^-b, which at order four reaches 0.3 by xi z = 1.7e-4 -- measured,
# and matching that prediction is what fixed the switch. The series needs
# |xi z| < 1 to converge and is cut at 0.2, where forty terms leave 1e-28 and
# the Leibniz form still carries 1e-13. The two agree in the overlap.

#' Derivative Components of the Generalized Pareto
#'
#' @description
#' Returns the components of
#' \eqn{\partial^{a+b}\ell/\partial\sigma^a\partial\xi^b} at any order from one
#' to four, by splitting the log-density into a part that is analytic at
#' \eqn{\xi = 0} and a part that carries a removable singularity there.
#'
#' @details
#' # The split
#'
#' With \eqn{z = y/\sigma} and \eqn{t = 1 + \xi z},
#' \deqn{\ell = -\log\sigma - L - W, \qquad L = \log t, \qquad W = L/\xi.}
#' \eqn{t} is affine in \eqn{\xi}, so every partial of it carrying two or more
#' \eqn{\xi} vanishes and the written-out template of [fdb2()] covers \eqn{L}
#' outright.
#'
#' # Why W has two routes
#'
#' \eqn{W = L/\xi} has a removable singularity at \eqn{\xi = 0}, where it tends
#' to \eqn{z}. Differentiating it by Leibniz,
#' \deqn{\partial^{a,b} W = \sum_{j} \binom{b}{j}\, \partial^{a,j}L \cdot
#'       \partial^{b-j}(1/\xi),}
#' produces terms of size \eqn{\xi^{-(b+1)}} that cancel against each other, so
#' near zero the form loses every digit. Below a threshold it is replaced by the
#' series the cancellation leaves,
#' \deqn{W = \sum_{k \ge 0} \frac{(-1)^k \xi^k z^{k+1}}{k+1},}
#' differentiated term by term.
#'
#' The threshold is on \eqn{\lvert\xi z\rvert} and **not** on \eqn{\xi}. At
#' order \eqn{b} the Leibniz terms are of size \eqn{z\xi^{-b}} against an answer
#' of size \eqn{z^{b+1}}, so the relative cancellation is
#' \eqn{(\xi z)^{-b}} and the accuracy is \eqn{\varepsilon(\xi z)^{-b}}, which
#' at order four reaches 0.3 by \eqn{\xi z = 1.7\times10^{-4}}. That prediction
#' was measured, and matching it is what fixed the switch. The series needs
#' \eqn{\lvert\xi z\rvert < 1} to converge and is cut at 0.2, where forty terms
#' leave \eqn{10^{-28}} while the Leibniz form still carries \eqn{10^{-13}}, so
#' the two overlap.
#'
#' # What the series branch evaluates
#'
#' The two elementwise powers the sum appears to need are algebraically one:
#' with \eqn{u = \xi z}, \eqn{\xi^{k-b}z^{k+1} = u^{k-b}z^{b+1}}, so
#' \eqn{z^{b+1}/\sigma^a} leaves the sum and what remains is a **polynomial in**
#' \eqn{u} whose coefficients are scalar in \eqn{k}. `gpd_poly_cpp()` evaluates
#' it by Horner from the highest power down, which sums a decaying series
#' smallest first. Each branch also runs on its own elements only, so a sample
#' straddling the cut does not pay for both in full.
#'
#' @param y A numeric vector of observations on the support.
#' @param theta A named list with components `sigma` and `xi`, each a numeric
#'   vector of length 1 or of the length of `y`. `sigma` must be strictly
#'   positive; `xi` may be of either sign, including zero, which is the
#'   exponential limit. Shorter components are recycled.
#' @param order The derivative order, an integer from 1 to 4.
#' @param cut The value of \eqn{\lvert\xi z\rvert} below which the series is
#'   used, defaulting to `0.2`. It is exposed so that a test can force either
#'   route in the region where both are accurate and compare them; a caller has
#'   no reason to change it.
#' @param threads A single positive integer, how many threads the polynomial
#'   kernel may use. Defaults to `1L`.
#'
#' @return A named list of component vectors, one per distinct multi-index of
#'   the given order and keyed as [deriv_names()] keys them: two at order 1,
#'   three at order 2, four at order 3 and five at order 4. Each has the
#'   recycled length of the inputs.
#'
#' @seealso [distrib_deriv3.GPDDistrib()] for the compiled kernels this
#'   assembly is checked against; [fdb2()] for the two-variable composition
#'   template; and
#'   [gpd_distrib()] for the family.
#' @keywords internal
gpd_components <- function(y, theta, order, cut = 0.2, threads = 1L) {
  sg <- theta[[1]]
  xi <- theta[[2]]
  n <- max(length(y), lengths(theta[1:2]))
  y <- rep_len(y, n)
  sg <- rep_len(sg, n)
  xi <- rep_len(xi, n)
  z <- y / sg
  t <- 1 + xi * z
  one <- rep_len(1, n)

  # L = log(t); t is affine in xi and a power series in 1/sigma, so every
  # partial of t with two or more xi vanishes. x stands for sigma, z for xi.
  # The Leibniz sum of W reads L's partials of every order up to `order`, so
  # fdb2() is called once per order and no higher one is formed.
  ut <- list(x = -xi * y / sg^2, z = y / sg)
  if (order >= 2L) { ut$xx <- 2 * xi * y / sg^3; ut$xz <- -y / sg^2 }
  if (order >= 3L) { ut$xxx <- -6 * xi * y / sg^4; ut$xxz <- 2 * y / sg^3 }
  if (order >= 4L) { ut$xxxx <- 24 * xi * y / sg^5; ut$xxxz <- -6 * y / sg^4 }
  hl <- lapply(seq_len(order), function(j) {
    (-1)^(j - 1L) * factorial(j - 1L) / t^j
  })
  Ld <- do.call(c, lapply(seq_len(order), function(o) fdb2(hl, ut, o)))
  Lget <- function(a, b) {
    if (a == 0L && b == 0L) return(base::log(t))
    v <- Ld[[paste0(strrep("x", a), strrep("z", b))]]
    if (is.null(v)) rep_len(0, n) else v * one
  }

  # W = L/xi, by Leibniz away from zero and by its own series near it
  small <- abs(xi * z) < cut
  rising <- function(m, a) {
    out <- rep_len(1, length(m))
    if (a >= 1L) for (i in 0:(a - 1L)) out <- out * (m + i)
    out
  }
  # Each branch runs on ITS OWN elements. Both used to be evaluated over the
  # whole vector and subset afterwards, so a sample straddling the cut paid
  # for both in full -- the arithmetic is elementwise, so subsetting first
  # returns the same numbers and does a fraction of the work.
  big_i <- which(!small)
  small_i <- which(small)
  Wget <- function(a, b) {
    out <- numeric(n)
    if (length(big_i)) {
      xi_i <- xi[big_i]
      acc <- numeric(length(big_i))
      for (j in 0:b) {
        m <- b - j
        acc <- acc + choose(b, j) * Lget(a, j)[big_i] * (-1)^m * factorial(m) /
          xi_i^(m + 1L)
      }
      out[big_i] <- acc
    }
    if (length(small_i)) {
      z_i <- z[small_i]
      u_i <- xi[small_i] * z_i
      # The two powers the loop used to raise PER ELEMENT are one power:
      # with u = xi z, xi^(k-b) z^(k+1) = u^(k-b) z^(b+1), so z^(b+1)/sigma^a
      # leaves the loop entirely and what is left is a POLYNOMIAL IN u whose
      # coefficients are scalar in k. Evaluating it is a scalar recursion of
      # forty-one steps per element, which is what gpd_poly_cpp() does by
      # Horner -- from the highest power down, so a decaying series is summed
      # smallest-first where the loop this replaces summed largest-first.
      # |u| < cut on this branch, so the powers decay and cannot overflow.
      ck <- vapply(b:40L, function(k) {
        (-1)^k * (factorial(k) / factorial(k - b)) * rising(k + 1, a) / (k + 1)
      }, 0)
      pref <- (-1)^a * z_i^(b + 1L) / sg[small_i]^a
      out[small_i] <- gpd_poly_cpp(u_i, ck, threads) * pref
    }
    out
  }

  comp <- function(a, b) {
    out <- -Lget(a, b) - Wget(a, b)
    if (b == 0L) {
      out <- out - if (a == 0L) base::log(sg) else
        (-1)^(a - 1L) * factorial(a - 1L) / sg^a
    }
    out
  }

  nms <- deriv_names(c("sigma", "xi"), order)
  stats::setNames(lapply(nms, function(nm) {
    parts <- strsplit(nm, "_")[[1]]
    comp(sum(parts == "sigma"), sum(parts == "xi"))
  }), nms)
}


#' @title Generalized Pareto Derivatives of Orders Three to Five
#' @name distrib_deriv3.GPDDistrib
#' @aliases distrib_deriv4.GPDDistrib distrib_deriv5.GPDDistrib
#'
#' @description
#' Return the third, fourth and fifth derivatives of the log-density in
#' \eqn{(\sigma, \xi)}, and for orders three and four their expectations, each
#' from its own compiled kernel.
#'
#' @details
#' With \eqn{z = y/\sigma}, \eqn{t = 1 + \xi z} and \eqn{u = \xi z}, the
#' log-density is \eqn{-\log\sigma - \log t - W} with
#' \eqn{W = \log(t)/\xi = z\,\phi(u)} and \eqn{\phi(u) = \log(1+u)/u}. Every
#' component is a closed form derived offline and written out, \eqn{\sigma^{-r}}
#' times a form in \eqn{z}, \eqn{\xi} and \eqn{1/t} for \eqn{r} derivatives in
#' \eqn{\sigma}. Since \eqn{\partial W/\partial z = 1/t}, only the pure
#' \eqn{\xi} component contains \eqn{\phi}, through
#' \eqn{\partial^j W/\partial\xi^j = z^{j+1}\phi^{(j)}(u)} with
#' \deqn{\phi^{(j)}(u) = \frac{(-1)^j j!}{u^{j+1}} \sum_{i > j}
#'   \frac{v^i}{i}, \qquad v = \frac{u}{1+u},}
#' summed as a series in \eqn{v} for \eqn{|v| \le 3/4} and as \eqn{\log t}
#' minus the first \eqn{j} terms elsewhere, so that no form divides by
#' \eqn{\xi} and \eqn{\xi = 0} is an ordinary point. \eqn{t} is formed from
#' the exact product \eqn{\xi y}, which keeps its relative accuracy near the
#' upper end of the support when \eqn{\xi < 0}.
#'
#' The expected derivatives follow from \eqn{V = (1 + \xi Y/\sigma)^{-1/\xi}},
#' uniform on \eqn{(0, 1)}: each is a rational function of \eqn{\xi} over
#' \eqn{\sigma^r}. They exist for \eqn{\xi > -1/3} at order three and
#' \eqn{\xi > -1/4} at order four, and are `NA` below; `approx` and `nsim` are
#' not read.
#'
#' Outside the support, \eqn{y < 0} or \eqn{1 + \xi y/\sigma \le 0}, every
#' component is `NaN`.
#'
#' @param distrib A `GPDDistrib` object, from [gpd_distrib()].
#' @param y A numeric vector of observations. With `expected = TRUE` only its
#'   length is read.
#' @param theta A named list with components `sigma` (positive) and `xi` (any
#'   real value), each a numeric vector of length 1 or of the length of `y`.
#' @param expected Logical of length 1; for orders three and four, whether the
#'   expectation under the model is returned. Defaults to `FALSE`.
#' @param scale `"parameter"` or `"link"`; the link scale is applied by the
#'   generic for orders three and four and by [deriv5_scale()] for order five.
#' @param approx,nsim Accepted for the generic's signature; the expectations
#'   are closed forms.
#' @param ... Unused.
#' @param threads A single positive integer, how many threads the compiled
#'   kernel may use. Defaults to `1L`. The result does not depend on the count.
#'
#' @return A named list with one numeric vector per component, keyed as
#'   [deriv_names()] keys them: 4, 5 and 6 components at orders three, four
#'   and five.
#'
#' @seealso [distrib_hessian.GPDDistrib()] for the order below,
#'   [gpd_components()] for an independent assembly of orders one to four, and
#'   [distrib_deriv3()] for the generic.
#'
#' @examples
#' d <- gpd_distrib()
#' y <- c(0.3, 1.5, 6)
#' th <- list(sigma = 1.5, xi = 0.3)
#' d3 <- distrib_deriv3(d, y, th)
#' names(d3)
#'
#' # A central difference of the Hessian reproduces the pure shape component.
#' eps <- 1e-5
#' up <- distrib_hessian(d, y, list(sigma = 1.5, xi = 0.3 + eps))$xi_xi
#' dn <- distrib_hessian(d, y, list(sigma = 1.5, xi = 0.3 - eps))$xi_xi
#' all.equal((up - dn) / (2 * eps), d3$xi_xi_xi, tolerance = 1e-6)
#'
#' # The shape zero is an ordinary point.
#' distrib_deriv4(d, y, list(sigma = 1.5, xi = 0))$xi_xi_xi_xi
#'
#' # The expected third derivatives, NA where they do not exist.
#' distrib_deriv3(d, 1, list(sigma = 1.5, xi = c(0.2, -0.4)),
#'                expected = TRUE)$xi_xi_xi
S7::method(distrib_deriv3, GPDDistrib) <- function(distrib, y, theta,
                                                    expected = FALSE,
                                                    scale = c("parameter", "link"),
                                                    approx = c("integrate", "bartlett", "mc", "opg"),
                                                    nsim = 10000, ..., threads = 1L) {
  if (expected) {
    gpd_deriv3_expected_cpp(y, theta[[1]], theta[[2]], threads)
  } else {
    gpd_deriv3_cpp(y, theta[[1]], theta[[2]], threads)
  }
}

S7::method(distrib_deriv4, GPDDistrib) <- function(distrib, y, theta,
                                                    expected = FALSE,
                                                    scale = c("parameter", "link"),
                                                    approx = c("integrate", "bartlett", "mc", "opg"),
                                                    nsim = 10000, ..., threads = 1L) {
  if (expected) {
    gpd_deriv4_expected_cpp(y, theta[[1]], theta[[2]], threads)
  } else {
    gpd_deriv4_cpp(y, theta[[1]], theta[[2]], threads)
  }
}

S7::method(distrib_deriv5, GPDDistrib) <- function(distrib, y, theta,
                                                    scale = c("parameter", "link"),
                                                    ..., threads = 1L) {
  deriv5_scale(distrib, y, theta,
               gpd_deriv5_cpp(y, theta[[1]], theta[[2]], threads),
               match.arg(scale))
}


#' @title Generalized Pareto Derivatives in the Response
#' @name distrib_grad_y.GPDDistrib
#' @aliases distrib_hess_y.GPDDistrib distrib_deriv3_y.GPDDistrib
#'   distrib_deriv4_y.GPDDistrib distrib_cross_y.GPDDistrib
#'   distrib_cross2_y.GPDDistrib distrib_grad_y_hess.GPDDistrib
#'   distrib_hess_y_hess.GPDDistrib
#'
#' @description
#' Return the derivatives of the log-density in the response to order four,
#' and the mixed derivatives of orders one and two in the response and one and
#' two in \eqn{(\sigma, \xi)}, each a closed form from its own compiled kernel.
#' The derivative in the response is
#' \eqn{\ell^{(y)} = -(1 + \xi)/(\sigma t)}, with \eqn{t = 1 + \xi y/\sigma},
#' so none of these forms divides by \eqn{\xi}; \eqn{t} is formed as
#' [distrib_deriv3.GPDDistrib()] describes. Outside the support every
#' component is `NaN`.
#'
#' @param distrib A `GPDDistrib` object, from [gpd_distrib()].
#' @param y A numeric vector of observations.
#' @param theta A named list with components `sigma` and `xi`, each a numeric
#'   vector of length 1 or of the length of `y`.
#' @param scale `"parameter"` or `"link"`, for the mixed derivatives; the link
#'   scale is applied by the generic.
#' @param ... Unused.
#'
#' @return A numeric vector for the derivatives in the response; a named list,
#'   keyed by parameter or by parameter pair in [hess_names()]'s order, for the
#'   mixed derivatives.
#'
#' @seealso [distrib_gradient.GPDDistrib()] for the derivatives in the
#'   parameters.
#'
#' @examples
#' d <- gpd_distrib()
#' th <- list(sigma = 1.5, xi = 0.3)
#' y <- c(0.3, 1.5, 6)
#' all.equal(distrib_grad_y(d, y, th), -(1 + 0.3) / (1.5 + 0.3 * y))
#' distrib_hess_y_hess(d, y, th)$xi_xi
S7::method(distrib_grad_y, GPDDistrib) <- function(distrib, y, theta, ...) {
  gpd_dy1_cpp(y, theta[[1]], theta[[2]])$y
}

S7::method(distrib_hess_y, GPDDistrib) <- function(distrib, y, theta, ...) {
  gpd_dy2_cpp(y, theta[[1]], theta[[2]])$y
}

S7::method(distrib_deriv3_y, GPDDistrib) <- function(distrib, y, theta, ...) {
  gpd_dy3_cpp(y, theta[[1]], theta[[2]])$y
}

S7::method(distrib_deriv4_y, GPDDistrib) <- function(distrib, y, theta, ...) {
  gpd_dy4_cpp(y, theta[[1]], theta[[2]])$y
}

S7::method(distrib_cross_y, GPDDistrib) <- function(
    distrib, y, theta, scale = c("parameter", "link"), ...) {
  gpd_cross_y_cpp(y, theta[[1]], theta[[2]])
}

S7::method(distrib_cross2_y, GPDDistrib) <- function(
    distrib, y, theta, scale = c("parameter", "link"), ...) {
  gpd_cross2_y_cpp(y, theta[[1]], theta[[2]])
}

S7::method(distrib_grad_y_hess, GPDDistrib) <- function(
    distrib, y, theta, scale = c("parameter", "link"), ...) {
  gpd_grad_y_hess_cpp(y, theta[[1]], theta[[2]])
}

S7::method(distrib_hess_y_hess, GPDDistrib) <- function(
    distrib, y, theta, scale = c("parameter", "link"), ...) {
  gpd_hess_y_hess_cpp(y, theta[[1]], theta[[2]])
}


#' @title Generalized Pareto Log-CDF Derivatives
#' @name distrib_grad_cdf.GPDDistrib
#' @aliases distrib_hess_cdf.GPDDistrib distrib_deriv3_cdf.GPDDistrib
#'   distrib_deriv4_cdf.GPDDistrib
#'
#' @description
#' Return the derivatives in \eqn{(\sigma, \xi)} of the distribution function
#' or of the survival function, or of their logarithms, at orders one to four,
#' each from its own compiled kernel.
#'
#' @details
#' The survival function is \eqn{S = e^{-W}} with
#' \eqn{W = z\,\phi(\xi z)} as [distrib_deriv3.GPDDistrib()] writes it, so
#' \eqn{\log S = -W} and its derivatives are those of \eqn{W}, free of any
#' division by \eqn{\xi}. The derivatives of \eqn{\log F = \log(1 - e^{-W})}
#' follow by Faa di Bruno with
#' \eqn{G(w) = \log(1 - e^{-w})}, whose derivatives are polynomials in
#' \eqn{q = 1/(e^{W} - 1)}: \eqn{G' = q} and \eqn{dq/dw = -q(1+q)}. Those of
#' \eqn{S} itself are \eqn{S} times the corresponding polynomial in the
#' derivatives of \eqn{-W}, and \eqn{\partial F = -\partial S}.
#'
#' At \eqn{\xi \ge 0} the support is \eqn{(0, \infty)}; at \eqn{\xi < 0} it is
#' bounded above at \eqn{\sigma/|\xi|}. Past the upper end, and below zero,
#' \eqn{F} is constant and every derivative is zero, except the derivatives of
#' \eqn{\log F} at \eqn{q \le 0}, where \eqn{\log F = -\infty} and they are
#' `NaN`.
#'
#' @param distrib A `GPDDistrib` object, from [gpd_distrib()].
#' @param q A numeric vector of quantiles.
#' @param theta A named list with components `sigma` (positive) and `xi` (any
#'   real value), each a numeric vector of length 1 or of the length of `q`.
#' @param lower.tail Logical; if `TRUE` (the default) the derivatives of
#'   \eqn{F}, otherwise those of \eqn{S = 1 - F}.
#' @param log Logical; if `TRUE` (the default) the derivatives of the
#'   logarithm.
#' @param ... Unused.
#'
#' @return A named list of numeric vectors keyed as
#'   [`deriv_names(distrib@params, order)`][deriv_names]: two components for
#'   the gradient, three for the Hessian, four at order three and five at order
#'   four.
#'
#' @seealso [distrib_grad_cdf.ExponentialDistrib()], the \eqn{\xi = 0} case;
#'   [gpd_distrib()].
#'
#' @usage NULL
#' @examples
#' d <- gpd_distrib()
#' q <- c(0.5, 2, 5)
#'
#' # At shape zero the scale component is the exponential family's.
#' rbind(gpd = distrib_grad_cdf(d, q, list(sigma = 3, xi = 0),
#'                              log = FALSE)$sigma,
#'       exponential = distrib_grad_cdf(exponential_distrib(), q,
#'                                      list(mu = 3), log = FALSE)$mu)
#'
#' # A negative shape bounds the support at sigma / |xi| = 2.
#' distrib_grad_cdf(d, c(1, 2, 3), list(sigma = 1, xi = -0.5),
#'                  log = FALSE)$sigma
#'
#' @keywords internal
gpd_cdf_method <- function(lower_log, upper_log, surv) {
  force(lower_log); force(upper_log); force(surv)
  function(distrib, q, theta, lower.tail = TRUE, log = TRUE, ...) {
    if (log) {
      if (lower.tail) lower_log(q, theta[[1]], theta[[2]])
      else upper_log(q, theta[[1]], theta[[2]])
    } else {
      s <- surv(q, theta[[1]], theta[[2]])
      if (lower.tail) lapply(s, function(v) -v) else s
    }
  }
}

# the kernels are wrapped, not passed: RcppExports.R may collate after this file
S7::method(distrib_grad_cdf, GPDDistrib) <- gpd_cdf_method(
  function(...) gpd_grad_cdf_lower_cpp(...), function(...) gpd_grad_cdf_upper_cpp(...),
  function(...) gpd_grad_surv_cpp(...))
S7::method(distrib_hess_cdf, GPDDistrib) <- gpd_cdf_method(
  function(...) gpd_hess_cdf_lower_cpp(...), function(...) gpd_hess_cdf_upper_cpp(...),
  function(...) gpd_hess_surv_cpp(...))
S7::method(distrib_deriv3_cdf, GPDDistrib) <- gpd_cdf_method(
  function(...) gpd_deriv3_cdf_lower_cpp(...), function(...) gpd_deriv3_cdf_upper_cpp(...),
  function(...) gpd_deriv3_surv_cpp(...))
S7::method(distrib_deriv4_cdf, GPDDistrib) <- gpd_cdf_method(
  function(...) gpd_deriv4_cdf_lower_cpp(...), function(...) gpd_deriv4_cdf_upper_cpp(...),
  function(...) gpd_deriv4_surv_cpp(...))
