# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gaussian_gradient_cpp <- function(y, mu, sigma) {
    .Call(`_distributions7_gaussian_gradient_cpp`, y, mu, sigma)
}

gaussian_hessian_cpp <- function(y, mu, sigma) {
    .Call(`_distributions7_gaussian_hessian_cpp`, y, mu, sigma)
}

gaussian_expected_hessian_cpp <- function(y, mu, sigma) {
    .Call(`_distributions7_gaussian_expected_hessian_cpp`, y, mu, sigma)
}

