# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bernoulli_gradient_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_bernoulli_gradient_cpp`, y, mu, threads)
}

bernoulli_hessian_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_bernoulli_hessian_cpp`, y, mu, threads)
}

bernoulli_expected_hessian_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_bernoulli_expected_hessian_cpp`, y, mu, threads)
}

bernoulli_deriv3_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_bernoulli_deriv3_cpp`, y, mu, threads)
}

bernoulli_deriv3_expected_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_bernoulli_deriv3_expected_cpp`, y, mu, threads)
}

bernoulli_deriv4_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_bernoulli_deriv4_cpp`, y, mu, threads)
}

bernoulli_deriv4_expected_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_bernoulli_deriv4_expected_cpp`, y, mu, threads)
}

beta_gradient_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_beta_gradient_cpp`, y, mu, phi, threads)
}

beta_hessian_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_beta_hessian_cpp`, y, mu, phi, threads)
}

beta_expected_hessian_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_beta_expected_hessian_cpp`, y, mu, phi, threads)
}

beta_dexpected1_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_beta_dexpected1_cpp`, y, mu, phi, threads)
}

beta_dexpected2_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_beta_dexpected2_cpp`, y, mu, phi, threads)
}

beta2_gradient_cpp <- function(y, alpha, beta, threads = 1L) {
    .Call(`_distributions7_beta2_gradient_cpp`, y, alpha, beta, threads)
}

beta2_hessian_cpp <- function(y, alpha, beta, threads = 1L) {
    .Call(`_distributions7_beta2_hessian_cpp`, y, alpha, beta, threads)
}

beta2_expected_hessian_cpp <- function(y, alpha, beta, threads = 1L) {
    .Call(`_distributions7_beta2_expected_hessian_cpp`, y, alpha, beta, threads)
}

beta_deriv3_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_beta_deriv3_cpp`, y, mu, phi, threads)
}

beta_deriv4_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_beta_deriv4_cpp`, y, mu, phi, threads)
}

betabinom_gradient_cpp <- function(y, mu, sigma, size, threads = 1L) {
    .Call(`_distributions7_betabinom_gradient_cpp`, y, mu, sigma, size, threads)
}

betabinom_hessian_cpp <- function(y, mu, sigma, size, threads = 1L) {
    .Call(`_distributions7_betabinom_hessian_cpp`, y, mu, sigma, size, threads)
}

betabinom_expected_hessian_cpp <- function(y, mu, sigma, size, threads = 1L) {
    .Call(`_distributions7_betabinom_expected_hessian_cpp`, y, mu, sigma, size, threads)
}

betabinom_logpmf_cpp <- function(y, mu, sigma, size, threads = 1L) {
    .Call(`_distributions7_betabinom_logpmf_cpp`, y, mu, sigma, size, threads)
}

binomial_gradient_cpp <- function(y, mu, size, threads = 1L) {
    .Call(`_distributions7_binomial_gradient_cpp`, y, mu, size, threads)
}

binomial_hessian_cpp <- function(y, mu, size, threads = 1L) {
    .Call(`_distributions7_binomial_hessian_cpp`, y, mu, size, threads)
}

binomial_expected_hessian_cpp <- function(y, mu, size, threads = 1L) {
    .Call(`_distributions7_binomial_expected_hessian_cpp`, y, mu, size, threads)
}

binomial_deriv3_cpp <- function(y, mu, size, threads = 1L) {
    .Call(`_distributions7_binomial_deriv3_cpp`, y, mu, size, threads)
}

binomial_deriv3_expected_cpp <- function(y, mu, size, threads = 1L) {
    .Call(`_distributions7_binomial_deriv3_expected_cpp`, y, mu, size, threads)
}

binomial_deriv4_cpp <- function(y, mu, size, threads = 1L) {
    .Call(`_distributions7_binomial_deriv4_cpp`, y, mu, size, threads)
}

binomial_deriv4_expected_cpp <- function(y, mu, size, threads = 1L) {
    .Call(`_distributions7_binomial_deriv4_expected_cpp`, y, mu, size, threads)
}

cauchy_gradient_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_cauchy_gradient_cpp`, y, mu, sigma, threads)
}

cauchy_hessian_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_cauchy_hessian_cpp`, y, mu, sigma, threads)
}

cauchy_expected_hessian_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_cauchy_expected_hessian_cpp`, y, mu, sigma, threads)
}

cauchy_deriv3_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_cauchy_deriv3_cpp`, y, mu, sigma, threads)
}

cauchy_deriv3_expected_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_cauchy_deriv3_expected_cpp`, y, mu, sigma, threads)
}

cauchy_deriv4_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_cauchy_deriv4_cpp`, y, mu, sigma, threads)
}

cauchy_deriv4_expected_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_cauchy_deriv4_expected_cpp`, y, mu, sigma, threads)
}

chisq_gradient_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_chisq_gradient_cpp`, y, mu, threads)
}

chisq_hessian_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_chisq_hessian_cpp`, y, mu, threads)
}

chisq_deriv3_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_chisq_deriv3_cpp`, y, mu, threads)
}

chisq_deriv4_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_chisq_deriv4_cpp`, y, mu, threads)
}

d7_scalar_probe <- function(cls, k, y, theta) {
    .Call(`_distributions7_d7_scalar_probe`, cls, k, y, theta)
}

d7_info_probe <- function(cls, k, y, theta) {
    .Call(`_distributions7_d7_info_probe`, cls, k, y, theta)
}

d7_scalar_classes_covered <- function() {
    .Call(`_distributions7_d7_scalar_classes_covered`)
}

bernoulli_dexpected1_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_bernoulli_dexpected1_cpp`, y, mu, threads)
}

bernoulli_dexpected2_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_bernoulli_dexpected2_cpp`, y, mu, threads)
}

binomial_dexpected1_cpp <- function(y, mu, size, threads = 1L) {
    .Call(`_distributions7_binomial_dexpected1_cpp`, y, mu, size, threads)
}

binomial_dexpected2_cpp <- function(y, mu, size, threads = 1L) {
    .Call(`_distributions7_binomial_dexpected2_cpp`, y, mu, size, threads)
}

exponential_dexpected1_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_exponential_dexpected1_cpp`, y, mu, threads)
}

exponential_dexpected2_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_exponential_dexpected2_cpp`, y, mu, threads)
}

geometric_dexpected1_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_geometric_dexpected1_cpp`, y, mu, threads)
}

geometric_dexpected2_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_geometric_dexpected2_cpp`, y, mu, threads)
}

chisq_dexpected1_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_chisq_dexpected1_cpp`, y, mu, threads)
}

chisq_dexpected2_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_chisq_dexpected2_cpp`, y, mu, threads)
}

cauchy_dexpected1_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_cauchy_dexpected1_cpp`, y, mu, sigma, threads)
}

cauchy_dexpected2_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_cauchy_dexpected2_cpp`, y, mu, sigma, threads)
}

logistic_dexpected1_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_logistic_dexpected1_cpp`, y, mu, sigma, threads)
}

logistic_dexpected2_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_logistic_dexpected2_cpp`, y, mu, sigma, threads)
}

gumbel_dexpected1_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_gumbel_dexpected1_cpp`, y, mu, sigma, threads)
}

gumbel_dexpected2_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_gumbel_dexpected2_cpp`, y, mu, sigma, threads)
}

gaussian2_dexpected1_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_gaussian2_dexpected1_cpp`, y, mu, sigma2, threads)
}

gaussian2_dexpected2_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_gaussian2_dexpected2_cpp`, y, mu, sigma2, threads)
}

gaussian3_dexpected1_cpp <- function(y, mu, tau, threads = 1L) {
    .Call(`_distributions7_gaussian3_dexpected1_cpp`, y, mu, tau, threads)
}

gaussian3_dexpected2_cpp <- function(y, mu, tau, threads = 1L) {
    .Call(`_distributions7_gaussian3_dexpected2_cpp`, y, mu, tau, threads)
}

invgauss1_dexpected1_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_invgauss1_dexpected1_cpp`, y, mu, phi, threads)
}

invgauss1_dexpected2_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_invgauss1_dexpected2_cpp`, y, mu, phi, threads)
}

invgauss2_dexpected1_cpp <- function(y, mu, lambda, threads = 1L) {
    .Call(`_distributions7_invgauss2_dexpected1_cpp`, y, mu, lambda, threads)
}

invgauss2_dexpected2_cpp <- function(y, mu, lambda, threads = 1L) {
    .Call(`_distributions7_invgauss2_dexpected2_cpp`, y, mu, lambda, threads)
}

gamma2_dexpected1_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_gamma2_dexpected1_cpp`, y, mu, sigma2, threads)
}

gamma2_dexpected2_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_gamma2_dexpected2_cpp`, y, mu, sigma2, threads)
}

beta2_dexpected1_cpp <- function(y, alpha, beta, threads = 1L) {
    .Call(`_distributions7_beta2_dexpected1_cpp`, y, alpha, beta, threads)
}

beta2_dexpected2_cpp <- function(y, alpha, beta, threads = 1L) {
    .Call(`_distributions7_beta2_dexpected2_cpp`, y, alpha, beta, threads)
}

weibull1_dexpected1_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_weibull1_dexpected1_cpp`, y, mu, sigma, threads)
}

weibull1_dexpected2_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_weibull1_dexpected2_cpp`, y, mu, sigma, threads)
}

gpd_dexpected1_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_dexpected1_cpp`, y, sigma, xi, threads)
}

gpd_dexpected2_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_dexpected2_cpp`, y, sigma, xi, threads)
}

betabinom_shapes_dexpected1_cpp <- function(y, alpha, beta, size, threads = 1L) {
    .Call(`_distributions7_betabinom_shapes_dexpected1_cpp`, y, alpha, beta, size, threads)
}

betabinom_shapes_dexpected2_cpp <- function(y, alpha, beta, size, threads = 1L) {
    .Call(`_distributions7_betabinom_shapes_dexpected2_cpp`, y, alpha, beta, size, threads)
}

enet_gradient_cpp <- function(y, mu, lambda, alpha, threads = 1L) {
    .Call(`_distributions7_enet_gradient_cpp`, y, mu, lambda, alpha, threads)
}

enet_hessian_cpp <- function(y, mu, lambda, alpha, threads = 1L) {
    .Call(`_distributions7_enet_hessian_cpp`, y, mu, lambda, alpha, threads)
}

enet_expected_hessian_cpp <- function(y, mu, lambda, alpha, threads = 1L) {
    .Call(`_distributions7_enet_expected_hessian_cpp`, y, mu, lambda, alpha, threads)
}

enet_dexpected1_cpp <- function(y, mu, lambda, alpha, threads = 1L) {
    .Call(`_distributions7_enet_dexpected1_cpp`, y, mu, lambda, alpha, threads)
}

exponential_gradient_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_exponential_gradient_cpp`, y, mu, threads)
}

exponential_hessian_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_exponential_hessian_cpp`, y, mu, threads)
}

exponential_expected_hessian_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_exponential_expected_hessian_cpp`, y, mu, threads)
}

exponential_deriv3_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_exponential_deriv3_cpp`, y, mu, threads)
}

exponential_deriv3_expected_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_exponential_deriv3_expected_cpp`, y, mu, threads)
}

exponential_deriv4_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_exponential_deriv4_cpp`, y, mu, threads)
}

exponential_deriv4_expected_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_exponential_deriv4_expected_cpp`, y, mu, threads)
}

gamma_gradient_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_gamma_gradient_cpp`, y, mu, sigma2, threads)
}

gamma_hessian_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_gamma_hessian_cpp`, y, mu, sigma2, threads)
}

gamma_expected_hessian_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_gamma_expected_hessian_cpp`, y, mu, sigma2, threads)
}

gamma1_gradient_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_gamma1_gradient_cpp`, y, mu, phi, threads)
}

gamma1_hessian_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_gamma1_hessian_cpp`, y, mu, phi, threads)
}

gamma1_expected_hessian_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_gamma1_expected_hessian_cpp`, y, mu, phi, threads)
}

gamma1_deriv3_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_gamma1_deriv3_cpp`, y, mu, phi, threads)
}

gamma1_deriv3_expected_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_gamma1_deriv3_expected_cpp`, y, mu, phi, threads)
}

gamma1_deriv4_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_gamma1_deriv4_cpp`, y, mu, phi, threads)
}

gamma1_dexpected1_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_gamma1_dexpected1_cpp`, y, mu, phi, threads)
}

gamma1_dexpected2_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_gamma1_dexpected2_cpp`, y, mu, phi, threads)
}

gamma1_deriv4_expected_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_gamma1_deriv4_expected_cpp`, y, mu, phi, threads)
}

gamma_deriv3_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_gamma_deriv3_cpp`, y, mu, sigma2, threads)
}

gamma_deriv3_expected_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_gamma_deriv3_expected_cpp`, y, mu, sigma2, threads)
}

gamma_deriv4_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_gamma_deriv4_cpp`, y, mu, sigma2, threads)
}

gamma_deriv4_expected_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_gamma_deriv4_expected_cpp`, y, mu, sigma2, threads)
}

gaussian_gradient_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_gaussian_gradient_cpp`, y, mu, sigma, threads)
}

gaussian_hessian_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_gaussian_hessian_cpp`, y, mu, sigma, threads)
}

gaussian_expected_hessian_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_gaussian_expected_hessian_cpp`, y, mu, sigma, threads)
}

gaussian_dexpected1_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_gaussian_dexpected1_cpp`, y, mu, sigma, threads)
}

gaussian_dexpected2_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_gaussian_dexpected2_cpp`, y, mu, sigma, threads)
}

gaussian2_gradient_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_gaussian2_gradient_cpp`, y, mu, sigma2, threads)
}

gaussian2_hessian_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_gaussian2_hessian_cpp`, y, mu, sigma2, threads)
}

gaussian2_expected_hessian_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_gaussian2_expected_hessian_cpp`, y, mu, sigma2, threads)
}

gaussian2_deriv3_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_gaussian2_deriv3_cpp`, y, mu, sigma2, threads)
}

gaussian2_deriv3_expected_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_gaussian2_deriv3_expected_cpp`, y, mu, sigma2, threads)
}

gaussian2_deriv4_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_gaussian2_deriv4_cpp`, y, mu, sigma2, threads)
}

gaussian2_deriv4_expected_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_gaussian2_deriv4_expected_cpp`, y, mu, sigma2, threads)
}

gaussian3_gradient_cpp <- function(y, mu, tau, threads = 1L) {
    .Call(`_distributions7_gaussian3_gradient_cpp`, y, mu, tau, threads)
}

gaussian3_hessian_cpp <- function(y, mu, tau, threads = 1L) {
    .Call(`_distributions7_gaussian3_hessian_cpp`, y, mu, tau, threads)
}

gaussian3_expected_hessian_cpp <- function(y, mu, tau, threads = 1L) {
    .Call(`_distributions7_gaussian3_expected_hessian_cpp`, y, mu, tau, threads)
}

gaussian3_deriv3_cpp <- function(y, mu, tau, threads = 1L) {
    .Call(`_distributions7_gaussian3_deriv3_cpp`, y, mu, tau, threads)
}

gaussian3_deriv4_cpp <- function(y, mu, tau, threads = 1L) {
    .Call(`_distributions7_gaussian3_deriv4_cpp`, y, mu, tau, threads)
}

gaussian_deriv3_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_gaussian_deriv3_cpp`, y, mu, sigma, threads)
}

gaussian_deriv3_expected_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_gaussian_deriv3_expected_cpp`, y, mu, sigma, threads)
}

gaussian_deriv4_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_gaussian_deriv4_cpp`, y, mu, sigma, threads)
}

gaussian_deriv4_expected_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_gaussian_deriv4_expected_cpp`, y, mu, sigma, threads)
}

gengamma_logpdf_cpp <- function(y, a, d, p, threads = 1L) {
    .Call(`_distributions7_gengamma_logpdf_cpp`, y, a, d, p, threads)
}

gengamma1_gradient_cpp <- function(y, a_, d_, p_, threads = 1L) {
    .Call(`_distributions7_gengamma1_gradient_cpp`, y, a_, d_, p_, threads)
}

gengamma1_hessian_cpp <- function(y, a_, d_, p_, threads = 1L) {
    .Call(`_distributions7_gengamma1_hessian_cpp`, y, a_, d_, p_, threads)
}

gengamma1_expected_hessian_cpp <- function(y, a_, d_, p_, threads = 1L) {
    .Call(`_distributions7_gengamma1_expected_hessian_cpp`, y, a_, d_, p_, threads)
}

gengamma1_deriv3_cpp <- function(y, a_, d_, p_, threads = 1L) {
    .Call(`_distributions7_gengamma1_deriv3_cpp`, y, a_, d_, p_, threads)
}

gengamma1_deriv3_expected_cpp <- function(y, a_, d_, p_, threads = 1L) {
    .Call(`_distributions7_gengamma1_deriv3_expected_cpp`, y, a_, d_, p_, threads)
}

gengamma1_deriv4_cpp <- function(y, a_, d_, p_, threads = 1L) {
    .Call(`_distributions7_gengamma1_deriv4_cpp`, y, a_, d_, p_, threads)
}

gengamma1_deriv4_expected_cpp <- function(y, a_, d_, p_, threads = 1L) {
    .Call(`_distributions7_gengamma1_deriv4_expected_cpp`, y, a_, d_, p_, threads)
}

gengamma1_deriv5_cpp <- function(y, a_, d_, p_, threads = 1L) {
    .Call(`_distributions7_gengamma1_deriv5_cpp`, y, a_, d_, p_, threads)
}

gengamma1_dexpected1_cpp <- function(y, a_, d_, p_, threads = 1L) {
    .Call(`_distributions7_gengamma1_dexpected1_cpp`, y, a_, d_, p_, threads)
}

gengamma1_dexpected2_cpp <- function(y, a_, d_, p_, threads = 1L) {
    .Call(`_distributions7_gengamma1_dexpected2_cpp`, y, a_, d_, p_, threads)
}

gengamma1_cross_y_cpp <- function(y, a_, d_, p_, threads = 1L) {
    .Call(`_distributions7_gengamma1_cross_y_cpp`, y, a_, d_, p_, threads)
}

gengamma1_cross2_y_cpp <- function(y, a_, d_, p_, threads = 1L) {
    .Call(`_distributions7_gengamma1_cross2_y_cpp`, y, a_, d_, p_, threads)
}

gengamma1_grad_y_hess_cpp <- function(y, a_, d_, p_, threads = 1L) {
    .Call(`_distributions7_gengamma1_grad_y_hess_cpp`, y, a_, d_, p_, threads)
}

gengamma1_hess_y_hess_cpp <- function(y, a_, d_, p_, threads = 1L) {
    .Call(`_distributions7_gengamma1_hess_y_hess_cpp`, y, a_, d_, p_, threads)
}

gengamma1_dy1_cpp <- function(y, a_, d_, p_, threads = 1L) {
    .Call(`_distributions7_gengamma1_dy1_cpp`, y, a_, d_, p_, threads)
}

gengamma1_dy2_cpp <- function(y, a_, d_, p_, threads = 1L) {
    .Call(`_distributions7_gengamma1_dy2_cpp`, y, a_, d_, p_, threads)
}

gengamma1_dy3_cpp <- function(y, a_, d_, p_, threads = 1L) {
    .Call(`_distributions7_gengamma1_dy3_cpp`, y, a_, d_, p_, threads)
}

gengamma1_dy4_cpp <- function(y, a_, d_, p_, threads = 1L) {
    .Call(`_distributions7_gengamma1_dy4_cpp`, y, a_, d_, p_, threads)
}

gengamma2_gradient_cpp <- function(y, mean_, d_, p_) {
    .Call(`_distributions7_gengamma2_gradient_cpp`, y, mean_, d_, p_)
}

gengamma2_hessian_cpp <- function(y, mean_, d_, p_) {
    .Call(`_distributions7_gengamma2_hessian_cpp`, y, mean_, d_, p_)
}

gengamma2_expected_hessian_cpp <- function(y, mean_, d_, p_) {
    .Call(`_distributions7_gengamma2_expected_hessian_cpp`, y, mean_, d_, p_)
}

gengamma2_deriv3_cpp <- function(y, mean_, d_, p_) {
    .Call(`_distributions7_gengamma2_deriv3_cpp`, y, mean_, d_, p_)
}

gengamma2_deriv3_expected_cpp <- function(y, mean_, d_, p_) {
    .Call(`_distributions7_gengamma2_deriv3_expected_cpp`, y, mean_, d_, p_)
}

gengamma2_deriv4_cpp <- function(y, mean_, d_, p_) {
    .Call(`_distributions7_gengamma2_deriv4_cpp`, y, mean_, d_, p_)
}

gengamma2_deriv4_expected_cpp <- function(y, mean_, d_, p_) {
    .Call(`_distributions7_gengamma2_deriv4_expected_cpp`, y, mean_, d_, p_)
}

gengamma2_deriv5_cpp <- function(y, mean_, d_, p_) {
    .Call(`_distributions7_gengamma2_deriv5_cpp`, y, mean_, d_, p_)
}

gengamma2_dexpected1_cpp <- function(y, mean_, d_, p_) {
    .Call(`_distributions7_gengamma2_dexpected1_cpp`, y, mean_, d_, p_)
}

gengamma2_dexpected2_cpp <- function(y, mean_, d_, p_) {
    .Call(`_distributions7_gengamma2_dexpected2_cpp`, y, mean_, d_, p_)
}

gengamma2_cross_y_cpp <- function(y, mean_, d_, p_) {
    .Call(`_distributions7_gengamma2_cross_y_cpp`, y, mean_, d_, p_)
}

gengamma2_cross2_y_cpp <- function(y, mean_, d_, p_) {
    .Call(`_distributions7_gengamma2_cross2_y_cpp`, y, mean_, d_, p_)
}

gengamma2_grad_y_hess_cpp <- function(y, mean_, d_, p_) {
    .Call(`_distributions7_gengamma2_grad_y_hess_cpp`, y, mean_, d_, p_)
}

gengamma2_hess_y_hess_cpp <- function(y, mean_, d_, p_) {
    .Call(`_distributions7_gengamma2_hess_y_hess_cpp`, y, mean_, d_, p_)
}

gengamma2_dy1_cpp <- function(y, mean_, d_, p_) {
    .Call(`_distributions7_gengamma2_dy1_cpp`, y, mean_, d_, p_)
}

gengamma2_dy2_cpp <- function(y, mean_, d_, p_) {
    .Call(`_distributions7_gengamma2_dy2_cpp`, y, mean_, d_, p_)
}

gengamma2_dy3_cpp <- function(y, mean_, d_, p_) {
    .Call(`_distributions7_gengamma2_dy3_cpp`, y, mean_, d_, p_)
}

gengamma2_dy4_cpp <- function(y, mean_, d_, p_) {
    .Call(`_distributions7_gengamma2_dy4_cpp`, y, mean_, d_, p_)
}

gengamma_logmean_cpp <- function(k, h) {
    .Call(`_distributions7_gengamma_logmean_cpp`, k, h)
}

gengamma_mu2_cpp <- function(k, h) {
    .Call(`_distributions7_gengamma_mu2_cpp`, k, h)
}

gengamma_mu3_cpp <- function(k, h) {
    .Call(`_distributions7_gengamma_mu3_cpp`, k, h)
}

gengamma_kappa4_cpp <- function(k, h) {
    .Call(`_distributions7_gengamma_kappa4_cpp`, k, h)
}

geometric_gradient_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_geometric_gradient_cpp`, y, mu, threads)
}

geometric_hessian_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_geometric_hessian_cpp`, y, mu, threads)
}

geometric_expected_hessian_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_geometric_expected_hessian_cpp`, y, mu, threads)
}

geometric_deriv3_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_geometric_deriv3_cpp`, y, mu, threads)
}

geometric_deriv3_expected_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_geometric_deriv3_expected_cpp`, y, mu, threads)
}

geometric_deriv4_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_geometric_deriv4_cpp`, y, mu, threads)
}

geometric_deriv4_expected_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_geometric_deriv4_expected_cpp`, y, mu, threads)
}

gpd_logpdf_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_logpdf_cpp`, y, sigma, xi, threads)
}

gpd_gradient_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_gradient_cpp`, y, sigma, xi, threads)
}

gpd_hessian_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_hessian_cpp`, y, sigma, xi, threads)
}

gpd_expected_hessian_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_expected_hessian_cpp`, y, sigma, xi, threads)
}

gpd_deriv3_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_deriv3_cpp`, y, sigma, xi, threads)
}

gpd_deriv3_expected_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_deriv3_expected_cpp`, y, sigma, xi, threads)
}

gpd_deriv4_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_deriv4_cpp`, y, sigma, xi, threads)
}

gpd_deriv4_expected_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_deriv4_expected_cpp`, y, sigma, xi, threads)
}

gpd_deriv5_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_deriv5_cpp`, y, sigma, xi, threads)
}

gpd_dy1_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_dy1_cpp`, y, sigma, xi, threads)
}

gpd_dy2_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_dy2_cpp`, y, sigma, xi, threads)
}

gpd_dy3_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_dy3_cpp`, y, sigma, xi, threads)
}

gpd_dy4_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_dy4_cpp`, y, sigma, xi, threads)
}

gpd_cross_y_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_cross_y_cpp`, y, sigma, xi, threads)
}

gpd_cross2_y_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_cross2_y_cpp`, y, sigma, xi, threads)
}

gpd_grad_y_hess_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_grad_y_hess_cpp`, y, sigma, xi, threads)
}

gpd_hess_y_hess_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_hess_y_hess_cpp`, y, sigma, xi, threads)
}

gpd_grad_cdf_lower_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_grad_cdf_lower_cpp`, y, sigma, xi, threads)
}

gpd_grad_cdf_upper_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_grad_cdf_upper_cpp`, y, sigma, xi, threads)
}

gpd_grad_surv_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_grad_surv_cpp`, y, sigma, xi, threads)
}

gpd_hess_cdf_lower_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_hess_cdf_lower_cpp`, y, sigma, xi, threads)
}

gpd_hess_cdf_upper_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_hess_cdf_upper_cpp`, y, sigma, xi, threads)
}

gpd_hess_surv_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_hess_surv_cpp`, y, sigma, xi, threads)
}

gpd_deriv3_cdf_lower_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_deriv3_cdf_lower_cpp`, y, sigma, xi, threads)
}

gpd_deriv3_cdf_upper_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_deriv3_cdf_upper_cpp`, y, sigma, xi, threads)
}

gpd_deriv3_surv_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_deriv3_surv_cpp`, y, sigma, xi, threads)
}

gpd_deriv4_cdf_lower_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_deriv4_cdf_lower_cpp`, y, sigma, xi, threads)
}

gpd_deriv4_cdf_upper_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_deriv4_cdf_upper_cpp`, y, sigma, xi, threads)
}

gpd_deriv4_surv_cpp <- function(y, sigma, xi, threads = 1L) {
    .Call(`_distributions7_gpd_deriv4_surv_cpp`, y, sigma, xi, threads)
}

gpd_poly_cpp <- function(u, coef, threads) {
    .Call(`_distributions7_gpd_poly_cpp`, u, coef, threads)
}

gumbel_gradient_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_gumbel_gradient_cpp`, y, mu, sigma, threads)
}

gumbel_hessian_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_gumbel_hessian_cpp`, y, mu, sigma, threads)
}

gumbel_expected_hessian_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_gumbel_expected_hessian_cpp`, y, mu, sigma, threads)
}

gumbel_deriv3_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_gumbel_deriv3_cpp`, y, mu, sigma, threads)
}

gumbel_deriv3_expected_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_gumbel_deriv3_expected_cpp`, y, mu, sigma, threads)
}

gumbel_deriv4_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_gumbel_deriv4_cpp`, y, mu, sigma, threads)
}

gumbel_deriv4_expected_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_gumbel_deriv4_expected_cpp`, y, mu, sigma, threads)
}

invgauss_gradient_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_invgauss_gradient_cpp`, y, mu, phi, threads)
}

invgauss_hessian_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_invgauss_hessian_cpp`, y, mu, phi, threads)
}

invgauss_expected_hessian_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_invgauss_expected_hessian_cpp`, y, mu, phi, threads)
}

invgauss2_gradient_cpp <- function(y, mu, lambda, threads = 1L) {
    .Call(`_distributions7_invgauss2_gradient_cpp`, y, mu, lambda, threads)
}

invgauss2_hessian_cpp <- function(y, mu, lambda, threads = 1L) {
    .Call(`_distributions7_invgauss2_hessian_cpp`, y, mu, lambda, threads)
}

invgauss2_expected_hessian_cpp <- function(y, mu, lambda, threads = 1L) {
    .Call(`_distributions7_invgauss2_expected_hessian_cpp`, y, mu, lambda, threads)
}

invgauss2_deriv3_cpp <- function(y, mu, lambda, expected, threads = 1L) {
    .Call(`_distributions7_invgauss2_deriv3_cpp`, y, mu, lambda, expected, threads)
}

invgauss2_deriv4_cpp <- function(y, mu, lambda, expected, threads = 1L) {
    .Call(`_distributions7_invgauss2_deriv4_cpp`, y, mu, lambda, expected, threads)
}

invgauss_deriv3_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_invgauss_deriv3_cpp`, y, mu, phi, threads)
}

invgauss_deriv3_expected_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_invgauss_deriv3_expected_cpp`, y, mu, phi, threads)
}

invgauss_deriv4_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_invgauss_deriv4_cpp`, y, mu, phi, threads)
}

invgauss_deriv4_expected_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_invgauss_deriv4_expected_cpp`, y, mu, phi, threads)
}

laplace_gradient_cpp <- function(y, mu, b, threads = 1L) {
    .Call(`_distributions7_laplace_gradient_cpp`, y, mu, b, threads)
}

laplace_hessian_cpp <- function(y, mu, b, threads = 1L) {
    .Call(`_distributions7_laplace_hessian_cpp`, y, mu, b, threads)
}

laplace_expected_hessian_cpp <- function(y, mu, b, threads = 1L) {
    .Call(`_distributions7_laplace_expected_hessian_cpp`, y, mu, b, threads)
}

laplace_dexpected1_cpp <- function(y, mu, b, threads = 1L) {
    .Call(`_distributions7_laplace_dexpected1_cpp`, y, mu, b, threads)
}

laplace_dexpected2_cpp <- function(y, mu, b, threads = 1L) {
    .Call(`_distributions7_laplace_dexpected2_cpp`, y, mu, b, threads)
}

laplace2_gradient_cpp <- function(y, mu, lambda, threads = 1L) {
    .Call(`_distributions7_laplace2_gradient_cpp`, y, mu, lambda, threads)
}

laplace2_hessian_cpp <- function(y, mu, lambda, threads = 1L) {
    .Call(`_distributions7_laplace2_hessian_cpp`, y, mu, lambda, threads)
}

laplace2_expected_hessian_cpp <- function(y, mu, lambda, threads = 1L) {
    .Call(`_distributions7_laplace2_expected_hessian_cpp`, y, mu, lambda, threads)
}

laplace2_dexpected1_cpp <- function(y, mu, lambda, threads = 1L) {
    .Call(`_distributions7_laplace2_dexpected1_cpp`, y, mu, lambda, threads)
}

laplace2_dexpected2_cpp <- function(y, mu, lambda, threads = 1L) {
    .Call(`_distributions7_laplace2_dexpected2_cpp`, y, mu, lambda, threads)
}

laplace_deriv3_cpp <- function(y, mu, b, threads = 1L) {
    .Call(`_distributions7_laplace_deriv3_cpp`, y, mu, b, threads)
}

laplace_deriv3_expected_cpp <- function(y, mu, b, threads = 1L) {
    .Call(`_distributions7_laplace_deriv3_expected_cpp`, y, mu, b, threads)
}

laplace_deriv4_cpp <- function(y, mu, b, threads = 1L) {
    .Call(`_distributions7_laplace_deriv4_cpp`, y, mu, b, threads)
}

laplace_deriv4_expected_cpp <- function(y, mu, b, threads = 1L) {
    .Call(`_distributions7_laplace_deriv4_expected_cpp`, y, mu, b, threads)
}

logistic_gradient_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_logistic_gradient_cpp`, y, mu, sigma, threads)
}

logistic_hessian_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_logistic_hessian_cpp`, y, mu, sigma, threads)
}

logistic_expected_hessian_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_logistic_expected_hessian_cpp`, y, mu, sigma, threads)
}

logistic_deriv3_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_logistic_deriv3_cpp`, y, mu, sigma, threads)
}

logistic_deriv4_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_logistic_deriv4_cpp`, y, mu, sigma, threads)
}

lognormal_gradient_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_lognormal_gradient_cpp`, y, mu, sigma2, threads)
}

lognormal_hessian_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_lognormal_hessian_cpp`, y, mu, sigma2, threads)
}

lognormal_expected_hessian_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_lognormal_expected_hessian_cpp`, y, mu, sigma2, threads)
}

lognormal2_gradient_cpp <- function(y, mean, var) {
    .Call(`_distributions7_lognormal2_gradient_cpp`, y, mean, var)
}

lognormal2_hessian_cpp <- function(y, mean, var) {
    .Call(`_distributions7_lognormal2_hessian_cpp`, y, mean, var)
}

lognormal2_expected_hessian_cpp <- function(y, mean, var) {
    .Call(`_distributions7_lognormal2_expected_hessian_cpp`, y, mean, var)
}

lognormal2_deriv3_cpp <- function(y, mean, var) {
    .Call(`_distributions7_lognormal2_deriv3_cpp`, y, mean, var)
}

lognormal2_deriv3_expected_cpp <- function(y, mean, var) {
    .Call(`_distributions7_lognormal2_deriv3_expected_cpp`, y, mean, var)
}

lognormal2_deriv4_cpp <- function(y, mean, var) {
    .Call(`_distributions7_lognormal2_deriv4_cpp`, y, mean, var)
}

lognormal2_deriv4_expected_cpp <- function(y, mean, var) {
    .Call(`_distributions7_lognormal2_deriv4_expected_cpp`, y, mean, var)
}

lognormal2_deriv5_cpp <- function(y, mean, var) {
    .Call(`_distributions7_lognormal2_deriv5_cpp`, y, mean, var)
}

lognormal2_dexpected1_cpp <- function(y, mean, var) {
    .Call(`_distributions7_lognormal2_dexpected1_cpp`, y, mean, var)
}

lognormal2_dexpected2_cpp <- function(y, mean, var) {
    .Call(`_distributions7_lognormal2_dexpected2_cpp`, y, mean, var)
}

lognormal2_dcdf1_cpp <- function(y, mean, var) {
    .Call(`_distributions7_lognormal2_dcdf1_cpp`, y, mean, var)
}

lognormal2_dcdf2_cpp <- function(y, mean, var) {
    .Call(`_distributions7_lognormal2_dcdf2_cpp`, y, mean, var)
}

lognormal2_dcdf3_cpp <- function(y, mean, var) {
    .Call(`_distributions7_lognormal2_dcdf3_cpp`, y, mean, var)
}

lognormal2_dcdf4_cpp <- function(y, mean, var) {
    .Call(`_distributions7_lognormal2_dcdf4_cpp`, y, mean, var)
}

lognormal2_cross_y_cpp <- function(y, mean, var) {
    .Call(`_distributions7_lognormal2_cross_y_cpp`, y, mean, var)
}

lognormal2_cross2_y_cpp <- function(y, mean, var) {
    .Call(`_distributions7_lognormal2_cross2_y_cpp`, y, mean, var)
}

lognormal2_grad_y_hess_cpp <- function(y, mean, var) {
    .Call(`_distributions7_lognormal2_grad_y_hess_cpp`, y, mean, var)
}

lognormal2_hess_y_hess_cpp <- function(y, mean, var) {
    .Call(`_distributions7_lognormal2_hess_y_hess_cpp`, y, mean, var)
}

lognormal2_dy1_cpp <- function(y, mean, var) {
    .Call(`_distributions7_lognormal2_dy1_cpp`, y, mean, var)
}

lognormal2_dy2_cpp <- function(y, mean, var) {
    .Call(`_distributions7_lognormal2_dy2_cpp`, y, mean, var)
}

lognormal2_dy3_cpp <- function(y, mean, var) {
    .Call(`_distributions7_lognormal2_dy3_cpp`, y, mean, var)
}

lognormal2_dy4_cpp <- function(y, mean, var) {
    .Call(`_distributions7_lognormal2_dy4_cpp`, y, mean, var)
}

lognormal_deriv3_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_lognormal_deriv3_cpp`, y, mu, sigma2, threads)
}

lognormal_deriv3_expected_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_lognormal_deriv3_expected_cpp`, y, mu, sigma2, threads)
}

lognormal_deriv4_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_lognormal_deriv4_cpp`, y, mu, sigma2, threads)
}

lognormal_deriv4_expected_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_lognormal_deriv4_expected_cpp`, y, mu, sigma2, threads)
}

negbin_dexpected1_cpp <- function(y, mu, theta, threads = 1L) {
    .Call(`_distributions7_negbin_dexpected1_cpp`, y, mu, theta, threads)
}

negbin_dexpected2_cpp <- function(y, mu, theta, threads = 1L) {
    .Call(`_distributions7_negbin_dexpected2_cpp`, y, mu, theta, threads)
}

negbin_gradient_cpp <- function(y, mu, theta, threads = 1L) {
    .Call(`_distributions7_negbin_gradient_cpp`, y, mu, theta, threads)
}

negbin_hessian_cpp <- function(y, mu, theta, threads = 1L) {
    .Call(`_distributions7_negbin_hessian_cpp`, y, mu, theta, threads)
}

negbin_expected_hessian_cpp <- function(y, mu, theta, threads = 1L) {
    .Call(`_distributions7_negbin_expected_hessian_cpp`, y, mu, theta, threads)
}

negbin1_logpmf_cpp <- function(y, mu, theta, threads = 1L) {
    .Call(`_distributions7_negbin1_logpmf_cpp`, y, mu, theta, threads)
}

negbin1_gradient_cpp <- function(y, mu, theta, threads = 1L) {
    .Call(`_distributions7_negbin1_gradient_cpp`, y, mu, theta, threads)
}

negbin1_hessian_cpp <- function(y, mu, theta, threads = 1L) {
    .Call(`_distributions7_negbin1_hessian_cpp`, y, mu, theta, threads)
}

negbin1_expected_hessian_cpp <- function(y, mu, theta, threads = 1L) {
    .Call(`_distributions7_negbin1_expected_hessian_cpp`, y, mu, theta, threads)
}

negbin1_dexpected1_cpp <- function(y, mu, theta, threads = 1L) {
    .Call(`_distributions7_negbin1_dexpected1_cpp`, y, mu, theta, threads)
}

negbin1_dexpected2_cpp <- function(y, mu, theta, threads = 1L) {
    .Call(`_distributions7_negbin1_dexpected2_cpp`, y, mu, theta, threads)
}

negbin1_psums_cpp <- function(y, mu, theta, order, threads = 1L) {
    .Call(`_distributions7_negbin1_psums_cpp`, y, mu, theta, order, threads)
}

negbin_deriv3_cpp <- function(y, mu, theta, threads = 1L) {
    .Call(`_distributions7_negbin_deriv3_cpp`, y, mu, theta, threads)
}

negbin_deriv3_expected_cpp <- function(y, mu, theta, threads = 1L) {
    .Call(`_distributions7_negbin_deriv3_expected_cpp`, y, mu, theta, threads)
}

negbin_deriv4_cpp <- function(y, mu, theta, threads = 1L) {
    .Call(`_distributions7_negbin_deriv4_cpp`, y, mu, theta, threads)
}

negbin_deriv4_expected_cpp <- function(y, mu, theta, threads = 1L) {
    .Call(`_distributions7_negbin_deriv4_expected_cpp`, y, mu, theta, threads)
}

pig1_hd_jet_cpp <- function(y, mu, sigma) {
    .Call(`_distributions7_pig1_hd_jet_cpp`, y, mu, sigma)
}

pig2_hd_jet_cpp <- function(y, mu, alpha) {
    .Call(`_distributions7_pig2_hd_jet_cpp`, y, mu, alpha)
}

pig1_pdf_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_pig1_pdf_cpp`, y, mu, sigma, threads)
}

pig1_gradient_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_pig1_gradient_cpp`, y, mu, sigma, threads)
}

pig1_hessian_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_pig1_hessian_cpp`, y, mu, sigma, threads)
}

pig1_deriv3_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_pig1_deriv3_cpp`, y, mu, sigma, threads)
}

pig1_deriv4_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_pig1_deriv4_cpp`, y, mu, sigma, threads)
}

pig1_hd_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_pig1_hd_cpp`, y, mu, sigma, threads)
}

pig2_pdf_cpp <- function(y, mu, alpha, threads = 1L) {
    .Call(`_distributions7_pig2_pdf_cpp`, y, mu, alpha, threads)
}

pig2_gradient_cpp <- function(y, mu, alpha, threads = 1L) {
    .Call(`_distributions7_pig2_gradient_cpp`, y, mu, alpha, threads)
}

pig2_hessian_cpp <- function(y, mu, alpha, threads = 1L) {
    .Call(`_distributions7_pig2_hessian_cpp`, y, mu, alpha, threads)
}

pig2_deriv3_cpp <- function(y, mu, alpha, threads = 1L) {
    .Call(`_distributions7_pig2_deriv3_cpp`, y, mu, alpha, threads)
}

pig2_deriv4_cpp <- function(y, mu, alpha, threads = 1L) {
    .Call(`_distributions7_pig2_deriv4_cpp`, y, mu, alpha, threads)
}

pig2_hd_cpp <- function(y, mu, alpha, threads = 1L) {
    .Call(`_distributions7_pig2_hd_cpp`, y, mu, alpha, threads)
}

pig2_expected_cpp <- function(y, mu, alpha, threads = 1L) {
    .Call(`_distributions7_pig2_expected_cpp`, y, mu, alpha, threads)
}

pig2_dexpected1_cpp <- function(y, mu, alpha, threads = 1L) {
    .Call(`_distributions7_pig2_dexpected1_cpp`, y, mu, alpha, threads)
}

pig2_dexpected2_cpp <- function(y, mu, alpha, threads = 1L) {
    .Call(`_distributions7_pig2_dexpected2_cpp`, y, mu, alpha, threads)
}

pig1_expected_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_pig1_expected_cpp`, y, mu, sigma, threads)
}

pig1_dexpected1_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_pig1_dexpected1_cpp`, y, mu, sigma, threads)
}

pig1_dexpected2_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_pig1_dexpected2_cpp`, y, mu, sigma, threads)
}

poisson_gradient_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_poisson_gradient_cpp`, y, mu, threads)
}

poisson_hessian_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_poisson_hessian_cpp`, y, mu, threads)
}

poisson_expected_hessian_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_poisson_expected_hessian_cpp`, y, mu, threads)
}

poisson_dexpected1_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_poisson_dexpected1_cpp`, y, mu, threads)
}

poisson_dexpected2_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_poisson_dexpected2_cpp`, y, mu, threads)
}

poisson_deriv3_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_poisson_deriv3_cpp`, y, mu, threads)
}

poisson_deriv3_expected_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_poisson_deriv3_expected_cpp`, y, mu, threads)
}

poisson_deriv4_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_poisson_deriv4_cpp`, y, mu, threads)
}

poisson_deriv4_expected_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_poisson_deriv4_expected_cpp`, y, mu, threads)
}

pseudohuber_gradient_cpp <- function(y, mu, sigma, nu) {
    .Call(`_distributions7_pseudohuber_gradient_cpp`, y, mu, sigma, nu)
}

pseudohuber_hessian_cpp <- function(y, mu, sigma, nu) {
    .Call(`_distributions7_pseudohuber_hessian_cpp`, y, mu, sigma, nu)
}

pseudohuber2_gradient_cpp <- function(y, mu, sigma, nu) {
    .Call(`_distributions7_pseudohuber2_gradient_cpp`, y, mu, sigma, nu)
}

pseudohuber2_hessian_cpp <- function(y, mu, sigma, nu) {
    .Call(`_distributions7_pseudohuber2_hessian_cpp`, y, mu, sigma, nu)
}

pseudohuber2_deriv3_cpp <- function(y, mu, sigma, nu) {
    .Call(`_distributions7_pseudohuber2_deriv3_cpp`, y, mu, sigma, nu)
}

pseudohuber2_deriv4_cpp <- function(y, mu, sigma, nu) {
    .Call(`_distributions7_pseudohuber2_deriv4_cpp`, y, mu, sigma, nu)
}

pseudohuber2_deriv5_cpp <- function(y, mu, sigma, nu) {
    .Call(`_distributions7_pseudohuber2_deriv5_cpp`, y, mu, sigma, nu)
}

pseudohuber2_nu_terms_cpp <- function(nu) {
    .Call(`_distributions7_pseudohuber2_nu_terms_cpp`, nu)
}

pseudohuber_deriv3_cpp <- function(y, mu, sigma, nu) {
    .Call(`_distributions7_pseudohuber_deriv3_cpp`, y, mu, sigma, nu)
}

pseudohuber_deriv4_cpp <- function(y, mu, sigma, nu) {
    .Call(`_distributions7_pseudohuber_deriv4_cpp`, y, mu, sigma, nu)
}

pseudohuber_rng_cpp <- function(n, mu, sigma1, nu) {
    .Call(`_distributions7_pseudohuber_rng_cpp`, n, mu, sigma1, nu)
}

pseudohuber_rou_box_cpp <- function(omega) {
    .Call(`_distributions7_pseudohuber_rou_box_cpp`, omega)
}

skewnormal1_gradient_cpp <- function(y, mu, sigma, alpha, threads = 1L) {
    .Call(`_distributions7_skewnormal1_gradient_cpp`, y, mu, sigma, alpha, threads)
}

skewnormal1_hessian_cpp <- function(y, mu, sigma, alpha, threads = 1L) {
    .Call(`_distributions7_skewnormal1_hessian_cpp`, y, mu, sigma, alpha, threads)
}

skewnormal2_expected_series_cpp <- function(sigma, gamma1) {
    .Call(`_distributions7_skewnormal2_expected_series_cpp`, sigma, gamma1)
}

skewnormal2_dexpected1_series_cpp <- function(sigma, gamma1) {
    .Call(`_distributions7_skewnormal2_dexpected1_series_cpp`, sigma, gamma1)
}

skewnormal2_dexpected2_series_cpp <- function(sigma, gamma1) {
    .Call(`_distributions7_skewnormal2_dexpected2_series_cpp`, sigma, gamma1)
}

skewnormal2_gradient_cpp <- function(y, mu, sigma, gamma1, threads = 1L) {
    .Call(`_distributions7_skewnormal2_gradient_cpp`, y, mu, sigma, gamma1, threads)
}

skewnormal2_hessian_cpp <- function(y, mu, sigma, gamma1, threads = 1L) {
    .Call(`_distributions7_skewnormal2_hessian_cpp`, y, mu, sigma, gamma1, threads)
}

skewnormal2_deriv3_cpp <- function(y, mu, sigma, gamma1, threads = 1L) {
    .Call(`_distributions7_skewnormal2_deriv3_cpp`, y, mu, sigma, gamma1, threads)
}

skewnormal2_deriv4_cpp <- function(y, mu, sigma, gamma1, threads = 1L) {
    .Call(`_distributions7_skewnormal2_deriv4_cpp`, y, mu, sigma, gamma1, threads)
}

skewnormal2_deriv5_cpp <- function(y, mu, sigma, gamma1, threads = 1L) {
    .Call(`_distributions7_skewnormal2_deriv5_cpp`, y, mu, sigma, gamma1, threads)
}

skewnormal2_cross_y_cpp <- function(y, mu, sigma, gamma1, threads = 1L) {
    .Call(`_distributions7_skewnormal2_cross_y_cpp`, y, mu, sigma, gamma1, threads)
}

skewnormal2_cross2_y_cpp <- function(y, mu, sigma, gamma1, threads = 1L) {
    .Call(`_distributions7_skewnormal2_cross2_y_cpp`, y, mu, sigma, gamma1, threads)
}

skewnormal2_grad_y_hess_cpp <- function(y, mu, sigma, gamma1, threads = 1L) {
    .Call(`_distributions7_skewnormal2_grad_y_hess_cpp`, y, mu, sigma, gamma1, threads)
}

skewnormal2_hess_y_hess_cpp <- function(y, mu, sigma, gamma1, threads = 1L) {
    .Call(`_distributions7_skewnormal2_hess_y_hess_cpp`, y, mu, sigma, gamma1, threads)
}

skewnormal2_dy1_cpp <- function(y, mu, sigma, gamma1, threads = 1L) {
    .Call(`_distributions7_skewnormal2_dy1_cpp`, y, mu, sigma, gamma1, threads)
}

skewnormal2_dy2_cpp <- function(y, mu, sigma, gamma1, threads = 1L) {
    .Call(`_distributions7_skewnormal2_dy2_cpp`, y, mu, sigma, gamma1, threads)
}

skewnormal2_dy3_cpp <- function(y, mu, sigma, gamma1, threads = 1L) {
    .Call(`_distributions7_skewnormal2_dy3_cpp`, y, mu, sigma, gamma1, threads)
}

skewnormal2_dy4_cpp <- function(y, mu, sigma, gamma1, threads = 1L) {
    .Call(`_distributions7_skewnormal2_dy4_cpp`, y, mu, sigma, gamma1, threads)
}

skewnormal_deriv3_cpp <- function(y, mu, sigma, alpha, threads = 1L) {
    .Call(`_distributions7_skewnormal_deriv3_cpp`, y, mu, sigma, alpha, threads)
}

skewnormal_deriv4_cpp <- function(y, mu, sigma, alpha, threads = 1L) {
    .Call(`_distributions7_skewnormal_deriv4_cpp`, y, mu, sigma, alpha, threads)
}

skewt_gradient_cpp <- function(y, mu, sigma, alpha, nu, threads = 1L) {
    .Call(`_distributions7_skewt_gradient_cpp`, y, mu, sigma, alpha, nu, threads)
}

skewt_hessian_cpp <- function(y, mu, sigma, alpha, nu, threads = 1L) {
    .Call(`_distributions7_skewt_hessian_cpp`, y, mu, sigma, alpha, nu, threads)
}

student_t1_gradient_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t1_gradient_cpp`, y, mu, sigma, nu, threads)
}

student_t1_hessian_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t1_hessian_cpp`, y, mu, sigma, nu, threads)
}

student_t1_expected_hessian_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t1_expected_hessian_cpp`, y, mu, sigma, nu, threads)
}

student_t1_deriv3_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t1_deriv3_cpp`, y, mu, sigma, nu, threads)
}

student_t1_deriv3_expected_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t1_deriv3_expected_cpp`, y, mu, sigma, nu, threads)
}

student_t1_deriv4_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t1_deriv4_cpp`, y, mu, sigma, nu, threads)
}

student_t1_deriv4_expected_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t1_deriv4_expected_cpp`, y, mu, sigma, nu, threads)
}

student_t1_deriv5_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t1_deriv5_cpp`, y, mu, sigma, nu, threads)
}

student_t1_dexpected1_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t1_dexpected1_cpp`, y, mu, sigma, nu, threads)
}

student_t1_dexpected2_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t1_dexpected2_cpp`, y, mu, sigma, nu, threads)
}

student_t1_cross_y_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t1_cross_y_cpp`, y, mu, sigma, nu, threads)
}

student_t1_cross2_y_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t1_cross2_y_cpp`, y, mu, sigma, nu, threads)
}

student_t1_grad_y_hess_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t1_grad_y_hess_cpp`, y, mu, sigma, nu, threads)
}

student_t1_hess_y_hess_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t1_hess_y_hess_cpp`, y, mu, sigma, nu, threads)
}

student_t1_dy1_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t1_dy1_cpp`, y, mu, sigma, nu, threads)
}

student_t1_dy2_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t1_dy2_cpp`, y, mu, sigma, nu, threads)
}

student_t1_dy3_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t1_dy3_cpp`, y, mu, sigma, nu, threads)
}

student_t1_dy4_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t1_dy4_cpp`, y, mu, sigma, nu, threads)
}

student_t2_gradient_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t2_gradient_cpp`, y, mu, sigma, nu, threads)
}

student_t2_hessian_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t2_hessian_cpp`, y, mu, sigma, nu, threads)
}

student_t2_expected_hessian_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t2_expected_hessian_cpp`, y, mu, sigma, nu, threads)
}

student_t2_deriv3_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t2_deriv3_cpp`, y, mu, sigma, nu, threads)
}

student_t2_deriv3_expected_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t2_deriv3_expected_cpp`, y, mu, sigma, nu, threads)
}

student_t2_deriv4_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t2_deriv4_cpp`, y, mu, sigma, nu, threads)
}

student_t2_deriv4_expected_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t2_deriv4_expected_cpp`, y, mu, sigma, nu, threads)
}

student_t2_deriv5_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t2_deriv5_cpp`, y, mu, sigma, nu, threads)
}

student_t2_dexpected1_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t2_dexpected1_cpp`, y, mu, sigma, nu, threads)
}

student_t2_dexpected2_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t2_dexpected2_cpp`, y, mu, sigma, nu, threads)
}

student_t2_cross_y_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t2_cross_y_cpp`, y, mu, sigma, nu, threads)
}

student_t2_cross2_y_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t2_cross2_y_cpp`, y, mu, sigma, nu, threads)
}

student_t2_grad_y_hess_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t2_grad_y_hess_cpp`, y, mu, sigma, nu, threads)
}

student_t2_hess_y_hess_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t2_hess_y_hess_cpp`, y, mu, sigma, nu, threads)
}

student_t2_dy1_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t2_dy1_cpp`, y, mu, sigma, nu, threads)
}

student_t2_dy2_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t2_dy2_cpp`, y, mu, sigma, nu, threads)
}

student_t2_dy3_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t2_dy3_cpp`, y, mu, sigma, nu, threads)
}

student_t2_dy4_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t2_dy4_cpp`, y, mu, sigma, nu, threads)
}

vonmises1_gradient_cpp <- function(y, mu, kappa, threads = 1L) {
    .Call(`_distributions7_vonmises1_gradient_cpp`, y, mu, kappa, threads)
}

vonmises1_hessian_cpp <- function(y, mu, kappa, threads = 1L) {
    .Call(`_distributions7_vonmises1_hessian_cpp`, y, mu, kappa, threads)
}

vonmises1_expected_hessian_cpp <- function(n, kappa, threads = 1L) {
    .Call(`_distributions7_vonmises1_expected_hessian_cpp`, n, kappa, threads)
}

vonmises1_deriv3_cpp <- function(y, mu, kappa, threads = 1L) {
    .Call(`_distributions7_vonmises1_deriv3_cpp`, y, mu, kappa, threads)
}

vonmises1_deriv4_cpp <- function(y, mu, kappa, threads = 1L) {
    .Call(`_distributions7_vonmises1_deriv4_cpp`, y, mu, kappa, threads)
}

vonmises1_dexpected1_cpp <- function(kappa, threads = 1L) {
    .Call(`_distributions7_vonmises1_dexpected1_cpp`, kappa, threads)
}

vonmises1_dexpected2_cpp <- function(kappa, threads = 1L) {
    .Call(`_distributions7_vonmises1_dexpected2_cpp`, kappa, threads)
}

vonmises2_gradient_cpp <- function(y, mu, rho, threads = 1L) {
    .Call(`_distributions7_vonmises2_gradient_cpp`, y, mu, rho, threads)
}

vonmises2_hessian_cpp <- function(y, mu, rho, threads = 1L) {
    .Call(`_distributions7_vonmises2_hessian_cpp`, y, mu, rho, threads)
}

vonmises2_expected_hessian_cpp <- function(n, rho, threads = 1L) {
    .Call(`_distributions7_vonmises2_expected_hessian_cpp`, n, rho, threads)
}

vonmises2_deriv3_cpp <- function(y, mu, rho, threads = 1L) {
    .Call(`_distributions7_vonmises2_deriv3_cpp`, y, mu, rho, threads)
}

vonmises2_deriv4_cpp <- function(y, mu, rho, threads = 1L) {
    .Call(`_distributions7_vonmises2_deriv4_cpp`, y, mu, rho, threads)
}

vonmises2_dexpected1_cpp <- function(rho, threads = 1L) {
    .Call(`_distributions7_vonmises2_dexpected1_cpp`, rho, threads)
}

vonmises2_dexpected2_cpp <- function(rho, threads = 1L) {
    .Call(`_distributions7_vonmises2_dexpected2_cpp`, rho, threads)
}

weibull1_gradient_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_weibull1_gradient_cpp`, y, mu, sigma, threads)
}

weibull1_hessian_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_weibull1_hessian_cpp`, y, mu, sigma, threads)
}

weibull1_expected_hessian_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_weibull1_expected_hessian_cpp`, y, mu, sigma, threads)
}

weibull3_gradient_cpp <- function(y, mean, sigma) {
    .Call(`_distributions7_weibull3_gradient_cpp`, y, mean, sigma)
}

weibull3_hessian_cpp <- function(y, mean, sigma) {
    .Call(`_distributions7_weibull3_hessian_cpp`, y, mean, sigma)
}

weibull3_expected_hessian_cpp <- function(y, mean, sigma) {
    .Call(`_distributions7_weibull3_expected_hessian_cpp`, y, mean, sigma)
}

weibull3_deriv3_cpp <- function(y, mean, sigma) {
    .Call(`_distributions7_weibull3_deriv3_cpp`, y, mean, sigma)
}

weibull3_deriv3_expected_cpp <- function(y, mean, sigma) {
    .Call(`_distributions7_weibull3_deriv3_expected_cpp`, y, mean, sigma)
}

weibull3_deriv4_cpp <- function(y, mean, sigma) {
    .Call(`_distributions7_weibull3_deriv4_cpp`, y, mean, sigma)
}

weibull3_deriv4_expected_cpp <- function(y, mean, sigma) {
    .Call(`_distributions7_weibull3_deriv4_expected_cpp`, y, mean, sigma)
}

weibull3_deriv5_cpp <- function(y, mean, sigma) {
    .Call(`_distributions7_weibull3_deriv5_cpp`, y, mean, sigma)
}

weibull3_dexpected1_cpp <- function(y, mean, sigma) {
    .Call(`_distributions7_weibull3_dexpected1_cpp`, y, mean, sigma)
}

weibull3_dexpected2_cpp <- function(y, mean, sigma) {
    .Call(`_distributions7_weibull3_dexpected2_cpp`, y, mean, sigma)
}

weibull3_dcdf1_cpp <- function(y, mean, sigma) {
    .Call(`_distributions7_weibull3_dcdf1_cpp`, y, mean, sigma)
}

weibull3_dcdf2_cpp <- function(y, mean, sigma) {
    .Call(`_distributions7_weibull3_dcdf2_cpp`, y, mean, sigma)
}

weibull3_dcdf3_cpp <- function(y, mean, sigma) {
    .Call(`_distributions7_weibull3_dcdf3_cpp`, y, mean, sigma)
}

weibull3_dcdf4_cpp <- function(y, mean, sigma) {
    .Call(`_distributions7_weibull3_dcdf4_cpp`, y, mean, sigma)
}

weibull3_cross_y_cpp <- function(y, mean, sigma) {
    .Call(`_distributions7_weibull3_cross_y_cpp`, y, mean, sigma)
}

weibull3_cross2_y_cpp <- function(y, mean, sigma) {
    .Call(`_distributions7_weibull3_cross2_y_cpp`, y, mean, sigma)
}

weibull3_grad_y_hess_cpp <- function(y, mean, sigma) {
    .Call(`_distributions7_weibull3_grad_y_hess_cpp`, y, mean, sigma)
}

weibull3_hess_y_hess_cpp <- function(y, mean, sigma) {
    .Call(`_distributions7_weibull3_hess_y_hess_cpp`, y, mean, sigma)
}

weibull3_dy1_cpp <- function(y, mean, sigma) {
    .Call(`_distributions7_weibull3_dy1_cpp`, y, mean, sigma)
}

weibull3_dy2_cpp <- function(y, mean, sigma) {
    .Call(`_distributions7_weibull3_dy2_cpp`, y, mean, sigma)
}

weibull3_dy3_cpp <- function(y, mean, sigma) {
    .Call(`_distributions7_weibull3_dy3_cpp`, y, mean, sigma)
}

weibull3_dy4_cpp <- function(y, mean, sigma) {
    .Call(`_distributions7_weibull3_dy4_cpp`, y, mean, sigma)
}

weibull_deriv3_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_weibull_deriv3_cpp`, y, mu, sigma, threads)
}

weibull_deriv3_expected_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_weibull_deriv3_expected_cpp`, y, mu, sigma, threads)
}

weibull_deriv4_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_weibull_deriv4_cpp`, y, mu, sigma, threads)
}

weibull_deriv4_expected_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_weibull_deriv4_expected_cpp`, y, mu, sigma, threads)
}

