# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bernoulli_gradient_cpp <- function(y, mu) {
    .Call(`_distributions7_bernoulli_gradient_cpp`, y, mu)
}

bernoulli_hessian_cpp <- function(y, mu) {
    .Call(`_distributions7_bernoulli_hessian_cpp`, y, mu)
}

bernoulli_expected_hessian_cpp <- function(y, mu) {
    .Call(`_distributions7_bernoulli_expected_hessian_cpp`, y, mu)
}

bernoulli_deriv3_cpp <- function(y, mu) {
    .Call(`_distributions7_bernoulli_deriv3_cpp`, y, mu)
}

bernoulli_deriv3_expected_cpp <- function(y, mu) {
    .Call(`_distributions7_bernoulli_deriv3_expected_cpp`, y, mu)
}

bernoulli_deriv4_cpp <- function(y, mu) {
    .Call(`_distributions7_bernoulli_deriv4_cpp`, y, mu)
}

bernoulli_deriv4_expected_cpp <- function(y, mu) {
    .Call(`_distributions7_bernoulli_deriv4_expected_cpp`, y, mu)
}

beta_gradient_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_beta_gradient_cpp`, y, mu, phi, threads)
}

beta_hessian_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_beta_hessian_cpp`, y, mu, phi, threads)
}

beta_expected_hessian_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_beta_expected_hessian_cpp`, y, mu, phi, threads)
}

beta_deriv3_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_beta_deriv3_cpp`, y, mu, phi, threads)
}

beta_deriv4_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_beta_deriv4_cpp`, y, mu, phi, threads)
}

betabinom_gradient_cpp <- function(y, mu, sigma, size, threads = 1L) {
    .Call(`_distributions7_betabinom_gradient_cpp`, y, mu, sigma, size, threads)
}

betabinom_hessian_cpp <- function(y, mu, sigma, size, threads = 1L) {
    .Call(`_distributions7_betabinom_hessian_cpp`, y, mu, sigma, size, threads)
}

betabinom_expected_hessian_cpp <- function(y, mu, sigma, size, threads = 1L) {
    .Call(`_distributions7_betabinom_expected_hessian_cpp`, y, mu, sigma, size, threads)
}

betabinom_logpmf_cpp <- function(y, mu, sigma, size, threads = 1L) {
    .Call(`_distributions7_betabinom_logpmf_cpp`, y, mu, sigma, size, threads)
}

binomial_gradient_cpp <- function(y, mu, size) {
    .Call(`_distributions7_binomial_gradient_cpp`, y, mu, size)
}

binomial_hessian_cpp <- function(y, mu, size) {
    .Call(`_distributions7_binomial_hessian_cpp`, y, mu, size)
}

binomial_expected_hessian_cpp <- function(y, mu, size) {
    .Call(`_distributions7_binomial_expected_hessian_cpp`, y, mu, size)
}

binomial_deriv3_cpp <- function(y, mu, size) {
    .Call(`_distributions7_binomial_deriv3_cpp`, y, mu, size)
}

binomial_deriv3_expected_cpp <- function(y, mu, size) {
    .Call(`_distributions7_binomial_deriv3_expected_cpp`, y, mu, size)
}

binomial_deriv4_cpp <- function(y, mu, size) {
    .Call(`_distributions7_binomial_deriv4_cpp`, y, mu, size)
}

binomial_deriv4_expected_cpp <- function(y, mu, size) {
    .Call(`_distributions7_binomial_deriv4_expected_cpp`, y, mu, size)
}

cauchy_gradient_cpp <- function(y, mu, sigma) {
    .Call(`_distributions7_cauchy_gradient_cpp`, y, mu, sigma)
}

cauchy_hessian_cpp <- function(y, mu, sigma) {
    .Call(`_distributions7_cauchy_hessian_cpp`, y, mu, sigma)
}

cauchy_expected_hessian_cpp <- function(y, mu, sigma) {
    .Call(`_distributions7_cauchy_expected_hessian_cpp`, y, mu, sigma)
}

cauchy_deriv3_cpp <- function(y, mu, sigma) {
    .Call(`_distributions7_cauchy_deriv3_cpp`, y, mu, sigma)
}

cauchy_deriv3_expected_cpp <- function(y, mu, sigma) {
    .Call(`_distributions7_cauchy_deriv3_expected_cpp`, y, mu, sigma)
}

cauchy_deriv4_cpp <- function(y, mu, sigma) {
    .Call(`_distributions7_cauchy_deriv4_cpp`, y, mu, sigma)
}

cauchy_deriv4_expected_cpp <- function(y, mu, sigma) {
    .Call(`_distributions7_cauchy_deriv4_expected_cpp`, y, mu, sigma)
}

chisq_gradient_cpp <- function(y, mu) {
    .Call(`_distributions7_chisq_gradient_cpp`, y, mu)
}

chisq_hessian_cpp <- function(y, mu) {
    .Call(`_distributions7_chisq_hessian_cpp`, y, mu)
}

chisq_deriv3_cpp <- function(y, mu) {
    .Call(`_distributions7_chisq_deriv3_cpp`, y, mu)
}

chisq_deriv4_cpp <- function(y, mu) {
    .Call(`_distributions7_chisq_deriv4_cpp`, y, mu)
}

d7_scalar_probe <- function(cls, k, y, theta) {
    .Call(`_distributions7_d7_scalar_probe`, cls, k, y, theta)
}

exponential_gradient_cpp <- function(y, mu) {
    .Call(`_distributions7_exponential_gradient_cpp`, y, mu)
}

exponential_hessian_cpp <- function(y, mu) {
    .Call(`_distributions7_exponential_hessian_cpp`, y, mu)
}

exponential_expected_hessian_cpp <- function(y, mu) {
    .Call(`_distributions7_exponential_expected_hessian_cpp`, y, mu)
}

exponential_deriv3_cpp <- function(y, mu) {
    .Call(`_distributions7_exponential_deriv3_cpp`, y, mu)
}

exponential_deriv3_expected_cpp <- function(y, mu) {
    .Call(`_distributions7_exponential_deriv3_expected_cpp`, y, mu)
}

exponential_deriv4_cpp <- function(y, mu) {
    .Call(`_distributions7_exponential_deriv4_cpp`, y, mu)
}

exponential_deriv4_expected_cpp <- function(y, mu) {
    .Call(`_distributions7_exponential_deriv4_expected_cpp`, y, mu)
}

gamma_gradient_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_gamma_gradient_cpp`, y, mu, sigma2, threads)
}

gamma_hessian_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_gamma_hessian_cpp`, y, mu, sigma2, threads)
}

gamma_expected_hessian_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_gamma_expected_hessian_cpp`, y, mu, sigma2, threads)
}

gamma1_gradient_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_gamma1_gradient_cpp`, y, mu, phi, threads)
}

gamma1_hessian_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_gamma1_hessian_cpp`, y, mu, phi, threads)
}

gamma1_expected_hessian_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_gamma1_expected_hessian_cpp`, y, mu, phi, threads)
}

gamma1_deriv3_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_gamma1_deriv3_cpp`, y, mu, phi, threads)
}

gamma1_deriv3_expected_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_gamma1_deriv3_expected_cpp`, y, mu, phi, threads)
}

gamma1_deriv4_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_gamma1_deriv4_cpp`, y, mu, phi, threads)
}

gamma1_deriv4_expected_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_gamma1_deriv4_expected_cpp`, y, mu, phi, threads)
}

gamma_deriv3_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_gamma_deriv3_cpp`, y, mu, sigma2, threads)
}

gamma_deriv3_expected_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_gamma_deriv3_expected_cpp`, y, mu, sigma2, threads)
}

gamma_deriv4_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_gamma_deriv4_cpp`, y, mu, sigma2, threads)
}

gamma_deriv4_expected_cpp <- function(y, mu, sigma2, threads = 1L) {
    .Call(`_distributions7_gamma_deriv4_expected_cpp`, y, mu, sigma2, threads)
}

gaussian_gradient_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_gaussian_gradient_cpp`, y, mu, sigma, threads)
}

gaussian_hessian_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_gaussian_hessian_cpp`, y, mu, sigma, threads)
}

gaussian_expected_hessian_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_gaussian_expected_hessian_cpp`, y, mu, sigma, threads)
}

gaussian2_gradient_cpp <- function(y, mu, sigma2) {
    .Call(`_distributions7_gaussian2_gradient_cpp`, y, mu, sigma2)
}

gaussian2_hessian_cpp <- function(y, mu, sigma2) {
    .Call(`_distributions7_gaussian2_hessian_cpp`, y, mu, sigma2)
}

gaussian2_expected_hessian_cpp <- function(y, mu, sigma2) {
    .Call(`_distributions7_gaussian2_expected_hessian_cpp`, y, mu, sigma2)
}

gaussian2_deriv3_cpp <- function(y, mu, sigma2) {
    .Call(`_distributions7_gaussian2_deriv3_cpp`, y, mu, sigma2)
}

gaussian2_deriv3_expected_cpp <- function(y, mu, sigma2) {
    .Call(`_distributions7_gaussian2_deriv3_expected_cpp`, y, mu, sigma2)
}

gaussian2_deriv4_cpp <- function(y, mu, sigma2) {
    .Call(`_distributions7_gaussian2_deriv4_cpp`, y, mu, sigma2)
}

gaussian2_deriv4_expected_cpp <- function(y, mu, sigma2) {
    .Call(`_distributions7_gaussian2_deriv4_expected_cpp`, y, mu, sigma2)
}

gaussian3_gradient_cpp <- function(y, mu, tau) {
    .Call(`_distributions7_gaussian3_gradient_cpp`, y, mu, tau)
}

gaussian3_hessian_cpp <- function(y, mu, tau) {
    .Call(`_distributions7_gaussian3_hessian_cpp`, y, mu, tau)
}

gaussian3_expected_hessian_cpp <- function(y, mu, tau) {
    .Call(`_distributions7_gaussian3_expected_hessian_cpp`, y, mu, tau)
}

gaussian3_deriv3_cpp <- function(y, mu, tau) {
    .Call(`_distributions7_gaussian3_deriv3_cpp`, y, mu, tau)
}

gaussian3_deriv4_cpp <- function(y, mu, tau) {
    .Call(`_distributions7_gaussian3_deriv4_cpp`, y, mu, tau)
}

gaussian_deriv3_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_gaussian_deriv3_cpp`, y, mu, sigma, threads)
}

gaussian_deriv3_expected_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_gaussian_deriv3_expected_cpp`, y, mu, sigma, threads)
}

gaussian_deriv4_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_gaussian_deriv4_cpp`, y, mu, sigma, threads)
}

gaussian_deriv4_expected_cpp <- function(y, mu, sigma, threads = 1L) {
    .Call(`_distributions7_gaussian_deriv4_expected_cpp`, y, mu, sigma, threads)
}

gengamma_logpdf_cpp <- function(y, a, d, p) {
    .Call(`_distributions7_gengamma_logpdf_cpp`, y, a, d, p)
}

gengamma_gradient_cpp <- function(y, a, d, p) {
    .Call(`_distributions7_gengamma_gradient_cpp`, y, a, d, p)
}

gengamma_hessian_cpp <- function(y, a, d, p) {
    .Call(`_distributions7_gengamma_hessian_cpp`, y, a, d, p)
}

gengamma_expected_hessian_cpp <- function(y, a, d, p) {
    .Call(`_distributions7_gengamma_expected_hessian_cpp`, y, a, d, p)
}

geometric_gradient_cpp <- function(y, mu) {
    .Call(`_distributions7_geometric_gradient_cpp`, y, mu)
}

geometric_hessian_cpp <- function(y, mu) {
    .Call(`_distributions7_geometric_hessian_cpp`, y, mu)
}

geometric_expected_hessian_cpp <- function(y, mu) {
    .Call(`_distributions7_geometric_expected_hessian_cpp`, y, mu)
}

geometric_deriv3_cpp <- function(y, mu) {
    .Call(`_distributions7_geometric_deriv3_cpp`, y, mu)
}

geometric_deriv3_expected_cpp <- function(y, mu) {
    .Call(`_distributions7_geometric_deriv3_expected_cpp`, y, mu)
}

geometric_deriv4_cpp <- function(y, mu) {
    .Call(`_distributions7_geometric_deriv4_cpp`, y, mu)
}

geometric_deriv4_expected_cpp <- function(y, mu) {
    .Call(`_distributions7_geometric_deriv4_expected_cpp`, y, mu)
}

gpd_logpdf_cpp <- function(y, sigma, xi) {
    .Call(`_distributions7_gpd_logpdf_cpp`, y, sigma, xi)
}

gpd_gradient_cpp <- function(y, sigma, xi) {
    .Call(`_distributions7_gpd_gradient_cpp`, y, sigma, xi)
}

gpd_hessian_cpp <- function(y, sigma, xi) {
    .Call(`_distributions7_gpd_hessian_cpp`, y, sigma, xi)
}

gpd_expected_hessian_cpp <- function(y, sigma, xi) {
    .Call(`_distributions7_gpd_expected_hessian_cpp`, y, sigma, xi)
}

gumbel_deriv3_cpp <- function(y, mu, sigma) {
    .Call(`_distributions7_gumbel_deriv3_cpp`, y, mu, sigma)
}

gumbel_deriv3_expected_cpp <- function(y, mu, sigma) {
    .Call(`_distributions7_gumbel_deriv3_expected_cpp`, y, mu, sigma)
}

gumbel_deriv4_cpp <- function(y, mu, sigma) {
    .Call(`_distributions7_gumbel_deriv4_cpp`, y, mu, sigma)
}

gumbel_deriv4_expected_cpp <- function(y, mu, sigma) {
    .Call(`_distributions7_gumbel_deriv4_expected_cpp`, y, mu, sigma)
}

invgauss_gradient_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_invgauss_gradient_cpp`, y, mu, phi, threads)
}

invgauss_hessian_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_invgauss_hessian_cpp`, y, mu, phi, threads)
}

invgauss_expected_hessian_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_invgauss_expected_hessian_cpp`, y, mu, phi, threads)
}

invgauss2_gradient_cpp <- function(y, mu, lambda) {
    .Call(`_distributions7_invgauss2_gradient_cpp`, y, mu, lambda)
}

invgauss2_hessian_cpp <- function(y, mu, lambda) {
    .Call(`_distributions7_invgauss2_hessian_cpp`, y, mu, lambda)
}

invgauss2_expected_hessian_cpp <- function(y, mu, lambda) {
    .Call(`_distributions7_invgauss2_expected_hessian_cpp`, y, mu, lambda)
}

invgauss2_deriv3_cpp <- function(y, mu, lambda, expected) {
    .Call(`_distributions7_invgauss2_deriv3_cpp`, y, mu, lambda, expected)
}

invgauss2_deriv4_cpp <- function(y, mu, lambda, expected) {
    .Call(`_distributions7_invgauss2_deriv4_cpp`, y, mu, lambda, expected)
}

invgauss_deriv3_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_invgauss_deriv3_cpp`, y, mu, phi, threads)
}

invgauss_deriv3_expected_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_invgauss_deriv3_expected_cpp`, y, mu, phi, threads)
}

invgauss_deriv4_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_invgauss_deriv4_cpp`, y, mu, phi, threads)
}

invgauss_deriv4_expected_cpp <- function(y, mu, phi, threads = 1L) {
    .Call(`_distributions7_invgauss_deriv4_expected_cpp`, y, mu, phi, threads)
}

laplace_deriv3_cpp <- function(y, mu, b) {
    .Call(`_distributions7_laplace_deriv3_cpp`, y, mu, b)
}

laplace_deriv3_expected_cpp <- function(y, mu, b) {
    .Call(`_distributions7_laplace_deriv3_expected_cpp`, y, mu, b)
}

laplace_deriv4_cpp <- function(y, mu, b) {
    .Call(`_distributions7_laplace_deriv4_cpp`, y, mu, b)
}

laplace_deriv4_expected_cpp <- function(y, mu, b) {
    .Call(`_distributions7_laplace_deriv4_expected_cpp`, y, mu, b)
}

logistic_gradient_cpp <- function(y, mu, sigma) {
    .Call(`_distributions7_logistic_gradient_cpp`, y, mu, sigma)
}

logistic_hessian_cpp <- function(y, mu, sigma) {
    .Call(`_distributions7_logistic_hessian_cpp`, y, mu, sigma)
}

logistic_expected_hessian_cpp <- function(y, mu, sigma) {
    .Call(`_distributions7_logistic_expected_hessian_cpp`, y, mu, sigma)
}

logistic_deriv3_cpp <- function(y, mu, sigma) {
    .Call(`_distributions7_logistic_deriv3_cpp`, y, mu, sigma)
}

logistic_deriv4_cpp <- function(y, mu, sigma) {
    .Call(`_distributions7_logistic_deriv4_cpp`, y, mu, sigma)
}

lognormal_gradient_cpp <- function(y, mu, sigma2) {
    .Call(`_distributions7_lognormal_gradient_cpp`, y, mu, sigma2)
}

lognormal_hessian_cpp <- function(y, mu, sigma2) {
    .Call(`_distributions7_lognormal_hessian_cpp`, y, mu, sigma2)
}

lognormal_expected_hessian_cpp <- function(y, mu, sigma2) {
    .Call(`_distributions7_lognormal_expected_hessian_cpp`, y, mu, sigma2)
}

lognormal_deriv3_cpp <- function(y, mu, sigma2) {
    .Call(`_distributions7_lognormal_deriv3_cpp`, y, mu, sigma2)
}

lognormal_deriv3_expected_cpp <- function(y, mu, sigma2) {
    .Call(`_distributions7_lognormal_deriv3_expected_cpp`, y, mu, sigma2)
}

lognormal_deriv4_cpp <- function(y, mu, sigma2) {
    .Call(`_distributions7_lognormal_deriv4_cpp`, y, mu, sigma2)
}

lognormal_deriv4_expected_cpp <- function(y, mu, sigma2) {
    .Call(`_distributions7_lognormal_deriv4_expected_cpp`, y, mu, sigma2)
}

negbin_gradient_cpp <- function(y, mu, theta, threads = 1L) {
    .Call(`_distributions7_negbin_gradient_cpp`, y, mu, theta, threads)
}

negbin_hessian_cpp <- function(y, mu, theta, threads = 1L) {
    .Call(`_distributions7_negbin_hessian_cpp`, y, mu, theta, threads)
}

negbin_expected_hessian_cpp <- function(y, mu, theta, threads = 1L) {
    .Call(`_distributions7_negbin_expected_hessian_cpp`, y, mu, theta, threads)
}

negbin1_logpmf_cpp <- function(y, mu, theta, threads = 1L) {
    .Call(`_distributions7_negbin1_logpmf_cpp`, y, mu, theta, threads)
}

negbin1_gradient_cpp <- function(y, mu, theta, threads = 1L) {
    .Call(`_distributions7_negbin1_gradient_cpp`, y, mu, theta, threads)
}

negbin1_hessian_cpp <- function(y, mu, theta, threads = 1L) {
    .Call(`_distributions7_negbin1_hessian_cpp`, y, mu, theta, threads)
}

negbin1_expected_hessian_cpp <- function(y, mu, theta, threads = 1L) {
    .Call(`_distributions7_negbin1_expected_hessian_cpp`, y, mu, theta, threads)
}

negbin_deriv3_cpp <- function(y, mu, theta, threads = 1L) {
    .Call(`_distributions7_negbin_deriv3_cpp`, y, mu, theta, threads)
}

negbin_deriv3_expected_cpp <- function(y, mu, theta, threads = 1L) {
    .Call(`_distributions7_negbin_deriv3_expected_cpp`, y, mu, theta, threads)
}

negbin_deriv4_cpp <- function(y, mu, theta, threads = 1L) {
    .Call(`_distributions7_negbin_deriv4_cpp`, y, mu, theta, threads)
}

negbin_deriv4_expected_cpp <- function(y, mu, theta, threads = 1L) {
    .Call(`_distributions7_negbin_deriv4_expected_cpp`, y, mu, theta, threads)
}

pig1_hd_jet_cpp <- function(y, mu, sigma) {
    .Call(`_distributions7_pig1_hd_jet_cpp`, y, mu, sigma)
}

pig2_hd_jet_cpp <- function(y, mu, alpha) {
    .Call(`_distributions7_pig2_hd_jet_cpp`, y, mu, alpha)
}

pig1_hd_cpp <- function(y, mu, sigma) {
    .Call(`_distributions7_pig1_hd_cpp`, y, mu, sigma)
}

pig2_hd_cpp <- function(y, mu, alpha) {
    .Call(`_distributions7_pig2_hd_cpp`, y, mu, alpha)
}

poisson_gradient_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_poisson_gradient_cpp`, y, mu, threads)
}

poisson_hessian_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_poisson_hessian_cpp`, y, mu, threads)
}

poisson_expected_hessian_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_poisson_expected_hessian_cpp`, y, mu, threads)
}

poisson_deriv3_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_poisson_deriv3_cpp`, y, mu, threads)
}

poisson_deriv3_expected_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_poisson_deriv3_expected_cpp`, y, mu, threads)
}

poisson_deriv4_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_poisson_deriv4_cpp`, y, mu, threads)
}

poisson_deriv4_expected_cpp <- function(y, mu, threads = 1L) {
    .Call(`_distributions7_poisson_deriv4_expected_cpp`, y, mu, threads)
}

pseudohuber_gradient_cpp <- function(y, mu, sigma, nu) {
    .Call(`_distributions7_pseudohuber_gradient_cpp`, y, mu, sigma, nu)
}

pseudohuber_hessian_cpp <- function(y, mu, sigma, nu) {
    .Call(`_distributions7_pseudohuber_hessian_cpp`, y, mu, sigma, nu)
}

pseudohuber_deriv3_cpp <- function(y, mu, sigma, nu) {
    .Call(`_distributions7_pseudohuber_deriv3_cpp`, y, mu, sigma, nu)
}

pseudohuber_deriv4_cpp <- function(y, mu, sigma, nu) {
    .Call(`_distributions7_pseudohuber_deriv4_cpp`, y, mu, sigma, nu)
}

skewnormal_deriv3_cpp <- function(y, mu, sigma, alpha) {
    .Call(`_distributions7_skewnormal_deriv3_cpp`, y, mu, sigma, alpha)
}

skewnormal_deriv4_cpp <- function(y, mu, sigma, alpha) {
    .Call(`_distributions7_skewnormal_deriv4_cpp`, y, mu, sigma, alpha)
}

student_t_gradient_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t_gradient_cpp`, y, mu, sigma, nu, threads)
}

student_t_hessian_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t_hessian_cpp`, y, mu, sigma, nu, threads)
}

student_t_expected_hessian_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t_expected_hessian_cpp`, y, mu, sigma, nu, threads)
}

student_t_deriv3_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t_deriv3_cpp`, y, mu, sigma, nu, threads)
}

student_t_deriv4_cpp <- function(y, mu, sigma, nu, threads = 1L) {
    .Call(`_distributions7_student_t_deriv4_cpp`, y, mu, sigma, nu, threads)
}

weibull_deriv3_cpp <- function(y, mu, sigma) {
    .Call(`_distributions7_weibull_deriv3_cpp`, y, mu, sigma)
}

weibull_deriv3_expected_cpp <- function(y, mu, sigma) {
    .Call(`_distributions7_weibull_deriv3_expected_cpp`, y, mu, sigma)
}

weibull_deriv4_cpp <- function(y, mu, sigma) {
    .Call(`_distributions7_weibull_deriv4_cpp`, y, mu, sigma)
}

weibull_deriv4_expected_cpp <- function(y, mu, sigma) {
    .Call(`_distributions7_weibull_deriv4_expected_cpp`, y, mu, sigma)
}

